SonarSource/sonarlint-intellij

- src/main/java/org/sonarlint/intellij/config/global/SonarQubeServerEditor.java
I tested the new version 2.0.0 and discovered that with that version we are unable to use our SonarQube in the company due to the restriction of the Server URL to 50 characters.
Therefore this pull-request to increase this. What I asked myself is the reason to limit this setting to 50. Is this a limitation of the core library?
> Increased maximum length of SonarQube server configuration items

- .sonarsource.properties
Those properties are required because the project is build with Gradle.
> Add resource and jiraKey

- src/main/java/org/sonarlint/intellij/trigger/SonarLintCheckinHandler.java
The current Review dialog cannot be accessed using the keyboard.
This commit introduces **mnemonics**, the same as found in the Intellij Commit/Review dialog.
Screenshot of the change:
Default Intellij commit dialog:
> Add mnemonics to the Review dialog

- src/main/java/org/sonarlint/intellij/util/SonarLintUtils.java
For slow SonarQube server and big projects (we have around 4 mil. lines of code) SonarLint times out. Can we extend timeout to 10 minutes?
> Extend read timeout to 10 minutes

- src/main/java/org/sonarlint/intellij/ui/nodes/IssueNode.java
This commit fixes the bug that mentioned here:
[https://stackoverflow.com/questions/54946147/intellij-idea-sonarlint-icon-can-not-found](https://stackoverflow.com/questions/54946147/intellij-idea-sonarlint-icon-can-not-found)
StringUtil.toLowerCase uses defaultLocale. If default locale is TURKISH or something, icon become mınor12.png ( lowered I with doteless )
`
Icon cannot be found in '/images/severity/mınor12.png', aClass='class icons.SonarLintIcons'
java.lang.Throwable: Icon cannot be found in '/images/severity/mınor12.png', aClass='class icons.SonarLintIcons'
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:157)
at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
at …
> toLowerCase Locale bug fix

- src/main/java/org/sonarlint/intellij/issue/persistence/IssuePersistence.java
Tested with IDEA Community 2018.1, 2019.2 and WebStorm 2020.1 (in both full and "LightEdit" mode for the last one).
Deprecated method `Project.getBaseDir()` returns `null` in LightEdit mode, resulting in NPE with SonarLint < 4.6
> Try new API to get project base path, fix NPE in LightEdit mode

- src/main/java/org/sonarlint/intellij/trigger/MakeTrigger.java
- src/test/java/org/sonarlint/intellij/trigger/MakeTriggerTest.java
CompileContext::getProject was changed to @NotNull in
https://github.com/JetBrains/intellij-community/commit/07e8f9dacd61811216a109e89e1e20fd89f126f5#diff-1442c013914b9019d787cfcaef28615c
> Remove null check in MakeTrigger

- src/main/java/org/sonarlint/intellij/config/global/rules/RulesFilterModel.java
- src/test/java/org/sonarlint/intellij/config/global/rules/RulesFilterModelTest.java
I made sure that:
- search by rule key finds the exact rule (to avoid breaking the link in the rule description)
- all terms from the search criterion match (AND search)
- sub-words are matched (e.g "null" will match "nullpointerexception", "notnull", "nullable")
> SLI-433 Relax search criteria in rule configuration filter

- src/main/java/org/sonarlint/intellij/analysis/SonarLintTask.java
Some PSI operations are checking cancellation, so we can ends up with `ProcessCanceledException` at any time, and we should be careful to not log it as error, but simply return.
> Ensure no error log is created when cancelling

- its/src/test/kotlin/org/sonarlint/intellij/its/BaseUiTest.kt
- its/src/test/kotlin/org/sonarlint/intellij/its/fixtures/IdeaFrame.kt
The system property was introduced in mid-2020, we need to manually close the dialog prior those versions
> Re-add closing of tip of the day for UI tests

- clion/src/main/java/org/sonarlint/intellij/clion/AnalyzerConfiguration.java
- clion/src/test/java/org/sonarlint/intellij/clion/AnalyzerConfigurationTest.java
- src/main/resources/META-INF/plugin.xml
This is blocked by CPP-2455. Once the CFamily plugin is released, as far as I can see this is the only required change to enable clang-cl in CLion.
> SLI-851 Add support for clang-cl

- src/main/java/org/sonarlint/intellij/actions/ReviewSecurityHotspotAction.kt
- src/main/java/org/sonarlint/intellij/actions/SonarLintToolWindow.java
- src/main/java/org/sonarlint/intellij/editor/SonarExternalAnnotator.java
- src/main/java/org/sonarlint/intellij/ui/ReportPanel.java
- src/main/java/org/sonarlint/intellij/ui/SecurityHotspotsPanel.java
- src/main/java/org/sonarlint/intellij/ui/SonarLintRulePanel.kt
- src/main/java/org/sonarlint/intellij/ui/nodes/SummaryNode.java
- src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleHeaderPanel.kt
- src/main/java/org/sonarlint/intellij/ui/tree/SecurityHotspotTreeModelBuilder.java
- src/test/java/org/sonarlint/intellij/ui/tree/SecurityHotspotTreeModelBuilderTests.java
- Hide resolved security hotspots from the report tab
- Fix the status not being selected rightfully when updating from the report tab
- Only highlight security hotspot that are currently displayed in the security hotspot tab list
- Fix filtering when status is not supported
- Trigger highlighting on filter change
> SLI-950 Hide resolved hotspots from report, fix selection, fix highlight

- build.gradle.kts
- src/main/java/org/sonarlint/intellij/java/JavaAnalysisConfigurator.java
- src/test/java/org/sonarlint/intellij/analysis/JavaAnalysisConfiguratorInvalidEntryTests.java
- src/test/java/org/sonarlint/intellij/analysis/JavaAnalysisConfiguratorTests.java
Java analyzer update and logical change regarding the `sonar.java.enablePreview` property.
> SLI-936: Update Java analyzer

- src/main/java/org/sonarlint/intellij/util/SonarLintAppUtils.java
- src/test/java/org/sonarlint/intellij/util/SonarLintAppUtilsHeavyTests.kt
- src/test/java/org/sonarlint/intellij/util/SonarLintAppUtilsLightTests.kt
- src/test/java/org/sonarlint/intellij/util/SonarLintAppUtilsTests.java
Minor changes to the former solution to check for all module content roots and not the first one. Checking every content root is necessary when for example a source folder is outside of the main project, this can be achieved with Gradle very easily. The other option is to have a project span multiple drives in Windows (I have no idea why anybody should do that, but okey).
To test the easiest case (file inside module with one content root) and the second easiest case (file outside module with one content root) are implemented as light tests. The *corner case* test (file inside module with multiple content roots not connected to one another) was implemented as a heavy test, as `com.intellij.testFramework.HeavyPlatformTestCase` provides the best way to create a standalone module with …
> SLI-833: Reworked the former solution

- src/main/java/org/sonarlint/intellij/actions/SonarCancelAction.java
- src/main/java/org/sonarlint/intellij/analysis/Analysis.java
- src/main/java/org/sonarlint/intellij/analysis/AnalysisSubmitter.java
- src/main/java/org/sonarlint/intellij/analysis/FindingStreamer.java
- src/main/java/org/sonarlint/intellij/core/ServerIssueUpdater.java
- src/main/java/org/sonarlint/intellij/finding/hotspot/ServerSecurityHotspotUpdater.java
- src/main/java/org/sonarlint/intellij/tasks/FutureAwaitingTask.kt
- src/main/java/org/sonarlint/intellij/util/FutureUtils.java
- src/test/java/org/sonarlint/intellij/analysis/AnalysisTests.java
- src/test/java/org/sonarlint/intellij/core/ServerIssueUpdaterTests.java
Remove parameter `waitForServerFindings` and put true by default. As a result, we will always wait for the server matching to be finished before ending the analysis.
The drawback is that the analysis might stay blocked for up to 60 seconds (timeout duration for the tasks) when waiting for the server findings.
As a result, I improved the analysis cancellation process (currently, we check if the status is `CANCELLING` only during the analysis of the modules, and before waiting for the server findings, so pressing the cancel button during the fetching had no effect).
> SLI-958 Wait for server findings

- src/main/java/org/sonarlint/intellij/module/ModuleFileSystem.kt
- src/main/java/org/sonarlint/intellij/util/VirtualFileUtils.kt
- src/test/java/org/sonarlint/intellij/util/VirtualFileUtilsTests.kt
Binary files are explicetly ommited from being analyzed. `VirtualFileUtilsTests` extends `AbstractSonarLintHeavyTests` as using `AbstractSonarLintLightTests` did not work correctly 😞
> SLI-942: Don't analyze binary files

- .cirrus.yml
Restrict build to PR, default, dogfood and maintained branches, excluding working branches with no PR.
> BUILD-3063 do not build working branches with no PR

- .cirrus.yml
This script is doing the following:
Replacing version 9.0-SNAPSHOT with 9.0.0.$build_version
Which should not happen in this step.
> BUILD-3527 Do not override build version on Cirrus `validate_task`

- src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleParsingUtils.kt
Reproducible by setting a thread sleep inside the new thread starting when loading the rules.
This happens when we save the rule panel, on `apply()` we do a `reset()` that load a bunch of stuff, including rules in a background thread.
With some unfortunate timing, or by simulating a thread sleep, we see that the panel is disposed but the background thread keeps going and tries to register the parent (which is now disposed).
> SLI-1044 Check if rule panel is disposed when parsing description

- build.gradle.kts
Looking at Cirrus logs, we download every dependency from maven central (Sonar scanners, etc.). We should probably do it from Repox if the dependencies are available there.
> Dependencies should be downloaded from Repox in priority

- src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
- src/test/java/org/sonarlint/intellij/SonarLintIntelliJClientTests.kt
- src/test/testData/SonarLintIntelliJClientTests/sonar-project.properties
- `FileIndex.iterateContent()` -> Iteration methods ("iterateX") may be called outside of a read action (since iteration can take a long time), but they should be prepared to project model being changed in the middle of the iteration.
- `VirtualFile.children()` -> Gets the child files. The returned files are guaranteed to be valid, if the method is called in a read action.
> SLI-1286 Short UI freeze when listing project files

- src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[SonarLint Client RPC request executor,4,main] 1004599971 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1718815322
at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:156)
at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:107)
at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:912)
at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java: …
```
> Checking if file is test source should be in a read action

- README.md
- build.gradle.kts
It seems that our omnisharp-roslyn is not pushed on maven central, so I avoid the download of this dependency if user has not defined credentials to Repox
> SLI-1291 Allow external contributors to build SLI

- .github/workflows/release.yml
Split the old notification channel for the IntelliClipse squad
> NO-JIRA: Change Slack channel

- .cirrus/slack-notification.sh
The task name is now displayed instead of the id. Additionally the branch name is now more prominent.
> SLI-1305: Reworked the Slack notification

- .cirrus.yml
The nightly cronjob won't run on master anymore but on a dedicated branch "plugin-verifier".
Notifications will be received via slack.
> SLI-1428 Plugin verifier task should not hide the master pipeline state

- src/main/java/org/sonarlint/intellij/ui/AbstractIssuesPanel.java
[SLI-1521](https://sonarsource.atlassian.net/browse/SLI-1521)
[SLI-1521]: https://sonarsource.atlassian.net/browse/SLI-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1521 TreeUI should be accessed only from EDT

- clion-common/src/main/java/org/sonarlint/intellij/clion/common/AnalyzerConfiguration.java
- clion-common/src/test/java/org/sonarlint/intellij/clion/common/AnalyzerConfigurationTest.java
[SLI-1586](https://sonarsource.atlassian.net/browse/SLI-1586)
[SLI-1586]: https://sonarsource.atlassian.net/browse/SLI-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1586 Sanitize `preprocessorDefines` before giving it to the analyzer

- gradle/libs.versions.toml
- src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
- src/main/java/org/sonarlint/intellij/core/BackendService.kt
- src/test/java/org/sonarlint/intellij/core/BackendServiceTests.kt
[SLI-1611](https://sonarsource.atlassian.net/browse/SLI-1611)
[SLI-1611]: https://sonarsource.atlassian.net/browse/SLI-1611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1611 Tune the Garbage Collector to avoid high memory usage

- src/main/java/org/sonarlint/intellij/tasks/ServerDownloadProjectTask.java
- src/main/java/org/sonarlint/intellij/util/FutureUtils.java
- src/main/java/org/sonarlint/intellij/util/ThreadUtils.kt
[SLI-1630](https://sonarsource.atlassian.net/browse/SLI-1630)
[SLI-1630]: https://sonarsource.atlassian.net/browse/SLI-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1630 Download project list on background thread

- gradle/libs.versions.toml
- src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
- src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalOptionsPanel.java
- src/main/java/org/sonarlint/intellij/core/BackendService.kt
- src/main/java/org/sonarlint/intellij/trigger/SonarLintCheckinHandler.java
- src/main/resources/META-INF/plugin.xml
[SLI-1629](https://sonarsource.atlassian.net/browse/SLI-1629)
[SLI-1629]: https://sonarsource.atlassian.net/browse/SLI-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1629 Improve how Node.js is loaded

- common/src/main/java/org/sonarlint/intellij/common/vcs/VcsRepo.kt
- git/src/main/kotlin/org/sonarlint/intellij/git/GitRepo.kt
- gradle.properties
- gradle/libs.versions.toml
- src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
- src/main/resources/META-INF/plugin.xml
[SLI-1644](https://sonarsource.atlassian.net/browse/SLI-1644)
[SLI-1642](https://sonarsource.atlassian.net/browse/SLI-1642)
[SLI-1644]: https://sonarsource.atlassian.net/browse/SLI-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLI-1642]: https://sonarsource.atlassian.net/browse/SLI-1642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1644 SLI-1642 Release 10.11.1

- src/main/java/org/sonarlint/intellij/actions/SonarLintToolWindow.java
- src/main/java/org/sonarlint/intellij/finding/issue/vulnerabilities/TaintVulnerabilitiesCache.kt
- src/main/java/org/sonarlint/intellij/ui/vulnerabilities/TaintVulnerabilitiesPanel.kt
[SLI-1316](https://sonarsource.atlassian.net/browse/SLI-1316)
[SLI-1316]: https://sonarsource.atlassian.net/browse/SLI-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1316 Have a common way of computing resolved findings

- src/main/java/org/sonarlint/intellij/editor/EditorDecorator.kt
- src/main/java/org/sonarlint/intellij/ui/AbstractIssuesPanel.java
- src/main/java/org/sonarlint/intellij/ui/vulnerabilities/TaintVulnerabilitiesPanel.kt
[SLI-1661](https://sonarsource.atlassian.net/browse/SLI-1661)
[SLI-1661]: https://sonarsource.atlassian.net/browse/SLI-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1661 Location numbers should be displayed in the editor

- .cirrus.star
- .cirrus.yml
[SLI-1670](https://sonarsource.atlassian.net/browse/SLI-1670)
1. Update cirrus-module v2 to v3.
2. Do not call the deprecated AWS feature method parameters `subnet_id`.
3. It is recommended to not use `ec2_instance` or `eks_container` root keys.
[SLI-1670]: https://sonarsource.atlassian.net/browse/SLI-1670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1670 Migrate deprecated cirrus-module v2 to v3

- THIRD-PARTY-NOTICES
- build.gradle.kts
- gradle/libs.versions.toml
- src/main/java/org/sonarlint/intellij/core/BackendService.kt
- src/main/java/org/sonarlint/intellij/core/EnabledLanguages.kt
[SLI-1696](https://sonarsource.atlassian.net/browse/SLI-1696) [SLI-1666](https://sonarsource.atlassian.net/browse/SLI-1666)
[SLI-1696]: https://sonarsource.atlassian.net/browse/SLI-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLI-1666]: https://sonarsource.atlassian.net/browse/SLI-1666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1696 SLI-1666 Adapt to new C# analyzer packaging

- gradle.properties
- src/main/java/org/sonarlint/intellij/analysis/OnTheFlyFindingsHolder.kt
- src/main/java/org/sonarlint/intellij/ui/CurrentFilePanel.java
[SLI-1728](https://sonarsource.atlassian.net/browse/SLI-1728)
[SLI-1728]: https://sonarsource.atlassian.net/browse/SLI-1728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1728 Toolwindow icon should not be red when every files are closed

- src/main/resources/META-INF/plugin.xml
[SLI-1766](https://sonarsource.atlassian.net/browse/SLI-1766)
[SLI-1766]: https://sonarsource.atlassian.net/browse/SLI-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1766 Update change notes for 10.13.1

- src/main/java/org/sonarlint/intellij/core/EnabledLanguages.kt
- src/main/java/org/sonarlint/intellij/finding/TextRangeMatcher.java
- src/main/java/org/sonarlint/intellij/util/VirtualFileUtils.kt
- src/main/resources/META-INF/plugin-jupyter.xml
- src/main/resources/META-INF/plugin.xml
- src/test/java/org/sonarlint/intellij/finding/TextRangeMatcherTest.kt
- src/test/java/org/sonarlint/intellij/util/VirtualFileUtilsTests.kt
[SLI-1751](https://sonarsource.atlassian.net/browse/SLI-1751)
[SLI-1751]: https://sonarsource.atlassian.net/browse/SLI-1751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1751 Enable analysis for Jupyter when plugin is enabled

- src/main/java/org/sonarlint/intellij/config/global/wizard/ServerStep.form
- src/main/java/org/sonarlint/intellij/config/global/wizard/ServerStep.java
- src/main/java/org/sonarlint/intellij/documentation/SonarLintDocumentation.kt
- src/main/java/org/sonarlint/intellij/notifications/SonarLintProjectNotifications.kt
- src/main/java/org/sonarlint/intellij/telemetry/LinkTelemetry.kt
- src/main/java/org/sonarlint/intellij/util/HelpLabelUtils.kt
- src/test/java/org/sonarlint/intellij/documentation/SonarLintDocumentationTests.kt
[SLI-1790](https://sonarsource.atlassian.net/browse/SLI-1790)
[SLI-1790]: https://sonarsource.atlassian.net/browse/SLI-1790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1790 Promote SQC free plan inside the IDE extensions

- clion/src/main/java/org/sonarlint/intellij/clion/CLionAnalyzerConfiguration.java
- src/main/resources/META-INF/plugin.xml
[SLI-1810](https://sonarsource.atlassian.net/browse/SLI-1810)
[SLI-1810]: https://sonarsource.atlassian.net/browse/SLI-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1810 Update change notes

- its/projects/sample-ansible/HostNamespacesCheck/tasks/HostNamespacesCheck.yaml
- its/src/test/kotlin/org/sonarlint/intellij/its/tests/flavor/AnsibleTests.kt
- its/src/test/resources/ansible-issue.xml
- src/main/java/org/sonarlint/intellij/core/EnabledLanguages.kt
- src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleLanguages.kt
[SLI-1812](https://sonarsource.atlassian.net/browse/SLI-1812)
[SLI-1812]: https://sonarsource.atlassian.net/browse/SLI-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1812 Support for Ansible files

- src/main/java/org/sonarlint/intellij/documentation/SonarLintDocumentation.kt
[SLI-1829](https://sonarsource.atlassian.net/browse/SLI-1829)
Part of the rebranding efforts necessitates the update of the URL structure on the Docs website.
This change reflects part of that update.
A redirect has been added to address links from outside the product.
[SLI-1829]: https://sonarsource.atlassian.net/browse/SLI-1829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1829 URL slug rebranding update

- src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
[SLI-1816](https://sonarsource.atlassian.net/browse/SLI-1816)
[SLI-1816]: https://sonarsource.atlassian.net/browse/SLI-1816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1816 Interrupting the branch matching computation should not cause an error

- src/test/java/org/sonarlint/intellij/trigger/SonarLintCheckinHandlerTests.java
[SLI-1880](https://sonarsource.atlassian.net/browse/SLI-1880)
Toolwindow mock is being called because of stuff happening in the background (SLOOP is synchronizing connections for example), we don't need to check for this in our test. What matters is `ReturnResult.COMMIT`
[SLI-1880]: https://sonarsource.atlassian.net/browse/SLI-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1880 Avoid remaining flaky tests on CheckinHandler

- nodejs/src/main/java/org/sonarlint/intellij/nodejs/JavaScriptNodeJsProvider.kt
[SLI-1946](https://sonarsource.atlassian.net/browse/SLI-1946)
[SLI-1946]: https://sonarsource.atlassian.net/browse/SLI-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-1946 On Windows, Node.js path should include .exe in the path

- src/main/java/org/sonarlint/intellij/actions/ChangeDependencyRiskStatusAction.kt
- src/main/java/org/sonarlint/intellij/actions/SonarLintToolWindow.java
- src/main/java/org/sonarlint/intellij/finding/sca/LocalDependencyRisk.kt
- src/main/java/org/sonarlint/intellij/ui/risks/DependencyRisksPanel.kt
[SLI-2190](https://sonarsource.atlassian.net/browse/SLI-2190)
So that it does not interfere with `didChangeDependencyRisks` callback. Otherwise we don't get correct transitions suggested for a changed item after update.
[SLI-2190]: https://sonarsource.atlassian.net/browse/SLI-2190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SLI-2190 Remove forced UI update
