build.gradle
This allows to remove special configuration for JaCoCo.
=> Update Gradle plugin "org.jetbrains.intellij" to 0.30.0

gradle.properties, src/main/java/org/sonarlint/intellij/analysis/SonarLintAnalyzer.java, src/main/java/org/sonarlint/intellij/analysis/SonarLintJobManager.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectConfigurable.java, src/main/java/org/sonarlint/intellij/trigger/SonarLintCheckinHandler.java, src/main/java/org/sonarlint/intellij/util/SonarLintUtils.java, src/test/java/org/sonarlint/intellij/SonarTest.java, src/test/java/org/sonarlint/intellij/analysis/SonarLintAnalyzerTest.java
Won't compile until we have SLCore and SQ QA'ed
=> More improvements

src/main/java/org/sonarlint/intellij/actions/SonarAnalyzeChangedFilesAction.java, src/main/java/org/sonarlint/intellij/analysis/AnalysisCallback.java, src/main/java/org/sonarlint/intellij/analysis/SonarLintJob.java, src/main/java/org/sonarlint/intellij/analysis/SonarLintJobManager.java, src/main/java/org/sonarlint/intellij/analysis/SonarLintTask.java, src/main/java/org/sonarlint/intellij/issue/IssueProcessor.java, src/main/java/org/sonarlint/intellij/trigger/SonarLintCheckinHandler.java, src/main/java/org/sonarlint/intellij/trigger/SonarLintSubmitter.java, src/main/java/org/sonarlint/intellij/ui/ChangedFilesTabOpener.java, src/main/java/org/sonarlint/intellij/ui/SonarLintToolWindowFactory.java, src/test/java/org/sonarlint/intellij/actions/SonarAnalyzeChangedFilesActionTest.java, src/test/java/org/sonarlint/intellij/trigger/SonarLintCheckinHandlerTest.java
This also fixes a bug: we were doing the callback to display the currently-known issues in changed files before waiting that the analysis actually finished!
=> SLI-153 Open changed files view when action runs

src/main/java/org/sonarlint/intellij/analysis/AnalysisCallbackAggregator.java, src/main/java/org/sonarlint/intellij/trigger/SonarLintSubmitter.java, src/test/java/org/sonarlint/intellij/analysis/AnalysisCallbackAggregatorTest.java
I'm not too happy about this solution, but should do it.
Later we can try to make something more elegant
=> Combine results multiple analysis

build.gradle, src/main/java/org/sonarlint/intellij/analysis/SonarLintAnalyzer.java, src/main/java/org/sonarlint/intellij/core/ConnectedSonarLintFacade.java, src/main/java/org/sonarlint/intellij/core/SonarLintFacade.java, src/main/java/org/sonarlint/intellij/core/StandaloneSonarLintFacade.java
It seems too simple, am I missing something, or is there a better way?
=> SLI-199 Don't save files before analysis in standalone mode

gradle.properties, src/main/java/org/sonarlint/intellij/trigger/SonarLintSubmitter.java, src/main/resources/META-INF/plugin.xml, src/test/java/org/sonarlint/intellij/trigger/SonarLintSubmitterTest.java
Fix for the exception thrown when all files of a module are excluded by server configuration.
=> SLI-264 Bug fix for concurrent modification

src/main/java/org/sonarlint/intellij/ui/SonarLintRulePanel.java
Very hacky but hopefully it will finally fix the problem..
=> SLI-237 Description doesn't fit in the rule window

src/main/resources/META-INF/plugin.xml
HTML paragraphs inspired by other [open-source plugins](https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/b0c8a9f494b30d076f754f5b7712063a68b44384/google-cloud-tools-plugin/resources/META-INF/plugin.xml) (see [repo entry](https://plugins.jetbrains.com/plugin/8079-google-cloud-tools)).
=> SLI-287 - Update plugin description to fit value proposition

build.gradle, src/main/resources/META-INF/plugin.xml
Update to very latest release of SonarJava :smile:
=> SLI-335 Use SonarJava 5.14

build.gradle, its/src/test/java/org/sonarlint/intellij/its/StandaloneTest.java, src/main/resources/META-INF/plugin.xml
SLI-363 SonarJava 6.1
SLI-370 SonarPython 2.5
SLI-371 SonarJS 6.2
=> Update Java, Python, JS analyzers

src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectSettings.java
Tested with IDEA Ultimate:
- 2018.3.6
- 2019.2
- 2020.1
=> SLI-402 Fix deserialization of analysis properties in IJ 2020.x

src/main/java/org/sonarlint/intellij/ui/tree/FlowsTree.java
=> SLI-430 Single selection for locations

gradle.properties, src/main/java/org/sonarlint/intellij/analysis/SonarLintAnalyzer.java, src/main/java/org/sonarlint/intellij/config/global/SonarLintAboutPanel.java, src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalConfigurable.java, src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalOptionsPanel.java, src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalSettings.java, src/main/java/org/sonarlint/intellij/config/global/SonarQubeServerMgmtPanel.java, src/main/java/org/sonarlint/intellij/config/global/rules/RuleConfigurationPanel.java, src/main/java/org/sonarlint/intellij/config/global/rules/RulesTreeNode.java, src/main/java/org/sonarlint/intellij/core/AnalysisRequirementNotifications.java, src/main/java/org/sonarlint/intellij/core/ConnectedSonarLintFacade.java, src/main/java/org/sonarlint/intellij/core/NodeJsManager.java, src/main/java/org/sonarlint/intellij/core/ProjectBindingManager.java, src/main/java/org/sonarlint/intellij/core/SonarLintEngineFactory.java, src/main/java/org/sonarlint/intellij/core/SonarLintEngineManager.java, src/main/java/org/sonarlint/intellij/core/SonarLintFacade.java, src/main/java/org/sonarlint/intellij/core/StandaloneSonarLintFacade.java, src/main/java/org/sonarlint/intellij/tasks/ServerUpdateTask.java, src/main/java/org/sonarlint/intellij/telemetry/SonarLintTelemetry.java, src/main/java/org/sonarlint/intellij/telemetry/SonarLintTelemetryImpl.java, src/main/java/org/sonarlint/intellij/telemetry/TelemetryManagerProvider.java, src/main/java/org/sonarlint/intellij/ui/SonarLintProjectAnalyzersPanel.java, src/main/java/org/sonarlint/intellij/ui/SonarLintRulePanel.java, src/main/resources/META-INF/plugin.xml, src/test/java/org/sonarlint/intellij/config/global/SonarLintGlobalSettingsTest.java, src/test/java/org/sonarlint/intellij/config/global/rules/RulesTreeNodeTest.java, src/test/java/org/sonarlint/intellij/core/ConnectedSonarLintFacadeTest.java, src/test/java/org/sonarlint/intellij/core/StandaloneSonarLintFacadeTest.java
Better support for Node.js and JRE requirements
=> Node.js requirement

src/main/java/org/sonarlint/intellij/config/global/ServerConnectionMgmtPanel.java, src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalConfigurable.java, src/main/java/org/sonarlint/intellij/config/global/wizard/AuthStep.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ConfirmStep.form, src/main/java/org/sonarlint/intellij/config/global/wizard/ConfirmStep.java, src/main/java/org/sonarlint/intellij/config/global/wizard/NotificationsStep.form, src/main/java/org/sonarlint/intellij/config/global/wizard/NotificationsStep.java, src/main/java/org/sonarlint/intellij/config/global/wizard/OrganizationStep.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ServerConnectionWizard.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ServerStep.form, src/main/java/org/sonarlint/intellij/config/global/wizard/WizardModel.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectConfigurable.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectSettings.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectSettingsPanel.java, src/main/java/org/sonarlint/intellij/core/ProjectBindingManager.java, src/main/java/org/sonarlint/intellij/core/ProjectServerNotifications.java, src/main/java/org/sonarlint/intellij/core/UpdateChecker.java, src/main/java/org/sonarlint/intellij/tasks/BindingStorageUpdateTask.java, src/main/java/org/sonarlint/intellij/tasks/CheckNotificationsSupportedTask.java, src/main/java/org/sonarlint/intellij/tasks/ConnectionUpdateTask.java, src/main/java/org/sonarlint/intellij/tasks/GetOrganizationsTask.java, src/test/java/org/sonarlint/intellij/config/global/wizard/WizardModelTest.java, src/test/java/org/sonarlint/intellij/config/project/SonarLintProjectSettingsTest.java, src/test/java/org/sonarlint/intellij/core/ProjectBindingManagerTest.java, src/test/java/org/sonarlint/intellij/core/ServerIssueUpdaterTest.java, src/test/java/org/sonarlint/intellij/core/UpdateCheckerTest.java, src/test/java/org/sonarlint/intellij/issue/hotspot/SecurityHotspotOpenerTest.java
* Create a dedicated step in the connection wizard to configure notifications
* Add an action in the notifications popup to directly go editing notifications
=> SLI-464 More rework of dev notifications

build.gradle.kts
I hacked to produce blockmap files during the build. I have not tested yet if it works for real, it will be easier once it goes in master for dogfood.
I got inspiration from:
https://github.com/JetBrains/gradle-intellij-plugin/issues/586#issuecomment-763548475
and
https://github.com/JetBrains/gradle-intellij-plugin/issues/586#issuecomment-776830927
=> Create blockmap files

clion/src/main/java/org/sonarlint/intellij/clion/CFamilyAnalysisConfigurator.java, common/src/main/java/org/sonarlint/intellij/common/analysis/AnalysisConfigurator.java, common/src/main/java/org/sonarlint/intellij/common/analysis/ExcludeResult.java, common/src/main/java/org/sonarlint/intellij/common/analysis/FileExclusionContributor.java, src/main/java/org/sonarlint/intellij/analysis/DefaultClientInputFile.java, src/main/java/org/sonarlint/intellij/analysis/LocalFileExclusions.java, src/main/java/org/sonarlint/intellij/analysis/SonarLintAnalyzer.java, src/main/java/org/sonarlint/intellij/java/JavaAnalysisConfigurator.java, src/main/java/org/sonarlint/intellij/java/JavaModuleClasspath.java, src/main/java/org/sonarlint/intellij/trigger/SonarLintSubmitter.java, src/main/java/org/sonarlint/intellij/ui/AutoTriggerStatusPanel.java, src/main/resources/META-INF/plugin-clion.xml, src/main/resources/META-INF/plugin.xml, src/test/java/org/sonarlint/intellij/analysis/DefaultClientInputFileTest.java, src/test/java/org/sonarlint/intellij/analysis/JavaAnalysisConfiguratorInvalidEntryTests.java, src/test/java/org/sonarlint/intellij/analysis/JavaAnalysisConfiguratorTests.java, src/test/java/org/sonarlint/intellij/analysis/JavaAnalysisConfiguratorWithModularJdkTests.java, src/test/java/org/sonarlint/intellij/analysis/LocalFileExclusionsTest.java, src/test/java/org/sonarlint/intellij/trigger/SonarLintSubmitterTests.java
@mpaladin I have not yet manually tested, but I was wondering if you could already have a look, to see if this kind of extension point would work for you.
=> SLI-509 Change AnalysisConfigurator EP to allow forcing file language

src/main/java/org/sonarlint/intellij/analysis/LocalFileExclusions.java, src/main/java/org/sonarlint/intellij/analysis/SonarLintTask.java, src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalConfigurable.java, src/main/java/org/sonarlint/intellij/config/global/rules/RuleConfigurationPanel.java, src/main/java/org/sonarlint/intellij/core/ProjectServerNotificationsSubscriber.kt, src/main/java/org/sonarlint/intellij/editor/CodeAnalyzerRestarter.java, src/main/java/org/sonarlint/intellij/issue/IssueManager.java, src/main/java/org/sonarlint/intellij/issue/vulnerabilities/TaintVulnerabilitiesPresenter.kt, src/main/java/org/sonarlint/intellij/messages/IssueStoreListener.java, src/main/java/org/sonarlint/intellij/ui/CurrentFileController.java, src/test/java/org/sonarlint/intellij/core/ProjectServerNotificationsSubscriberTest.kt
* ReadAction error
* performance issue when displaying issues
* too many taint vulnerability refresh jobs created
=> Feedback from dogfood

build.gradle.kts, src/main/resources/META-INF/plugin.xml
Release notes: https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16739
=> Update sonar-cfamily-plugin to 6.20.0.31240

build.gradle.kts, gradle.properties, src/main/java/org/sonarlint/intellij/core/SonarLintEngineFactory.java
=> SLI-532 enable secrets analysis

src/main/java/org/sonarlint/intellij/trigger/SonarLintCheckinHandler.java
=> SLI-544 precommit check

build.gradle.kts, clion/src/main/java/org/sonarlint/intellij/clion/AnalyzerConfiguration.java, clion/src/main/java/org/sonarlint/intellij/clion/BuildWrapperJsonGenerator.java, clion/src/test/java/org/sonarlint/intellij/clion/AnalyzerConfigurationTest.java, clion/src/test/java/org/sonarlint/intellij/clion/BuildWrapperJsonGeneratorTest.java
CFamily release: https://jira.sonarsource.com/browse/REL-1944
=> SLI-545 Add support for MSVC compiler in CLion

build.gradle.kts, clion/build.gradle.kts, common/build.gradle.kts, its/build.gradle.kts
https://lp.jetbrains.com/gradle-intellij-plugin/
=> Update gradle-intellij-plugin to 1.1.2

azure-pipelines.yml, build.gradle.kts, gradle.properties, rider/build.gradle.kts, rider/src/main/java/org/sonarlint/intellij/rider/CsharpLanguageActivator.java, rider/src/main/java/org/sonarlint/intellij/rider/RiderAnalysisConfigurator.kt, settings.gradle.kts, src/main/java/org/sonarlint/intellij/actions/AbstractSonarAction.java, src/main/java/org/sonarlint/intellij/actions/ExcludeFileAction.java, src/main/java/org/sonarlint/intellij/actions/SonarAnalyzeFilesAction.java, src/main/java/org/sonarlint/intellij/core/SecurityHotspotMatcher.java, src/main/java/org/sonarlint/intellij/core/SonarLintEngineFactory.java, src/main/java/org/sonarlint/intellij/editor/SonarExternalAnnotator.java, src/main/java/org/sonarlint/intellij/fs/EditorFileChangeListener.kt, src/main/java/org/sonarlint/intellij/fs/VirtualFileSystemListener.kt, src/main/java/org/sonarlint/intellij/issue/vulnerabilities/TaintVulnerabilityMatcher.kt, src/main/java/org/sonarlint/intellij/ui/RecentProjectsPanel.kt, src/main/java/org/sonarlint/intellij/ui/SonarLintConsoleImpl.java, src/main/resources/META-INF/plugin-rider.xml, src/main/resources/META-INF/plugin.xml
=> Add support for C# analysis in Rider

clion/src/main/java/org/sonarlint/intellij/clion/AnalyzerConfiguration.java
=> SLI-559 Always add newline to preprocessorDefines property

build.gradle.kts, rider/src/main/java/org/sonarlint/intellij/rider/RiderAnalysisConfigurator.kt
Depends on https://github.com/SonarSource/sonarlint-omnisharp/pull/103
=> SLI-647 Pass the configured Mono runtime to OmniSharp

azure-pipelines.yml, build.gradle.kts, gradle.properties
BUILD-1449: use org.cyclonedx.bom Gradle plugin to generate an SBOM artifact attached to the build
=> BUILD-1440 sbom plugin

build.gradle.kts, rider/src/main/java/org/sonarlint/intellij/rider/RiderAnalysisConfigurator.kt, src/main/java/org/sonarlint/intellij/issue/persistence/IssuePersistence.java
Depends on https://github.com/SonarSource/sonarlint-omnisharp/pull/118
=> Hardening Rider #1

src/main/java/org/sonarlint/intellij/trigger/SonarLintCheckinHandler.java
Also rename the 'Close' option to 'Cancel' as it better describes the behaviour
=> SLI-759 Rename 'Commit anyway' option to 'Continue' in pre-commit dialog

src/main/java/org/sonarlint/intellij/ui/SecurityHotspotsPanel.java, src/main/java/org/sonarlint/intellij/ui/nodes/LiveSecurityHotspotNode.java
- Wrong icon color in case of locally detected hotspot
- Code smell for non static method
=> Fix icon color on Security Hotspot

src/main/java/org/sonarlint/intellij/editor/ApplyQuickFixIntentionAction.kt
I would like to add a test, but the Python analyzer with quick fixes on regexp is not yet released.
=> SLI-886 Fix application of quick fixes in injected languages

src/main/java/org/sonarlint/intellij/SonarLintIcons.kt, src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/actions/FilterSecurityHotspotActionGroup.java, src/main/java/org/sonarlint/intellij/actions/ReviewSecurityHotspotAction.kt, src/main/java/org/sonarlint/intellij/actions/SonarLintToolWindow.java, src/main/java/org/sonarlint/intellij/actions/filters/FilterSecurityHotspotSettings.java, src/main/java/org/sonarlint/intellij/actions/filters/SecurityHotspotFilters.java, src/main/java/org/sonarlint/intellij/actions/filters/ShowResolvedHotspotsAction.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectSettings.java, src/main/java/org/sonarlint/intellij/editor/SonarExternalAnnotator.java, src/main/java/org/sonarlint/intellij/finding/hotspot/LiveSecurityHotspot.java, src/main/java/org/sonarlint/intellij/finding/hotspot/ServerSecurityHotspotTrackable.java, src/main/java/org/sonarlint/intellij/finding/tracking/ServerFindingTracker.java, src/main/java/org/sonarlint/intellij/ui/SecurityHotspotsPanel.java, src/main/java/org/sonarlint/intellij/ui/SonarLintRulePanel.kt, src/main/java/org/sonarlint/intellij/ui/review/ReviewSecurityHotspotDialog.kt, src/main/java/org/sonarlint/intellij/ui/review/ReviewSecurityHotspotPanel.kt, src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleHeaderPanel.kt, src/main/java/org/sonarlint/intellij/ui/tree/SecurityHotspotTreeModelBuilder.java, src/main/java/org/sonarlint/intellij/util/SonarLintActions.java, src/main/resources/images/hotspot_checked.svg, src/main/resources/images/hotspot_checked_dark.svg, src/test/java/org/sonarlint/intellij/actions/FilterSecurityHotspotActionGroupTests.java
=> SLI-935 Introduce filter for resolved hotspots

src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleHeaderPanel.kt
=> SLI-941 fix review priority disappearance

build.gradle.kts, common/src/main/java/org/sonarlint/intellij/common/util/SonarLintUtils.java, its/src/test/kotlin/org/sonarlint/intellij/its/fixtures/RemoteRobotExtensions.kt, src/main/java/org/sonarlint/intellij/core/SonarLintEngineFactory.java, src/main/java/org/sonarlint/intellij/fs/EditorFileChangeListener.kt, src/main/java/org/sonarlint/intellij/fs/VirtualFileSystemListener.kt, src/main/java/org/sonarlint/intellij/util/SonarLintAppUtils.java
Cleanup / changes in the codebase based on the [Internal API Migration](https://plugins.jetbrains.com/docs/intellij/api-internal.html#plugins).
=> SLI-833: Remove use of internal API

build.gradle.kts, src/main/resources/META-INF/plugin.xml
Tests done with local project and new rule [S6529](https://sonarsource.atlassian.net/browse/SONARKT-297).
=> SLI-943: Update Kotlin analyzer

src/main/java/org/sonarlint/intellij/go/GoLanguageActivator.java
This resolves the issue not found when switching from Go support only for GoLand to supporting also the Go plugin in IntelliJ IDEA Ultimate.
=> SLI-940: Fixed Go plugin connection

src/main/java/org/sonarlint/intellij/ui/ReportPanel.java, src/main/java/org/sonarlint/intellij/ui/SonarLintRulePanel.kt
=> SLI-908 fix rule details exception

src/main/java/org/sonarlint/intellij/ui/ReportPanel.java
=> SLI-908-rework-former-solution

src/main/java/org/sonarlint/intellij/notifications/AnalysisRequirementNotifications.java, src/main/java/org/sonarlint/intellij/util/ProjectLogOutput.java, src/test/java/org/sonarlint/intellij/util/ProjectLogOutputTests.java
=> SLI-883 Remove special exception notification

build.gradle.kts, src/main/resources/META-INF/plugin.xml
- XML analyzer update in this repository
- C# analyzer update in [SonarSource/sonarlint-omnisharp](https://github.com/SonarSource/sonarlint-omnisharp/pull/154) repository
Testing was done for C# with rule S6618
=> SLI-962,SLI-967: Update XML and C# (Omnisharp) analyzer

src/main/java/org/sonarlint/intellij/actions/MarkAsResolvedAction.kt, src/main/java/org/sonarlint/intellij/actions/OpenIssueInBrowserAction.kt, src/main/java/org/sonarlint/intellij/finding/issue/LiveIssue.java, src/main/java/org/sonarlint/intellij/ui/SonarLintRulePanel.kt, src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleHeaderPanel.kt, src/main/java/org/sonarlint/intellij/ui/tree/IssueTree.java, src/main/java/org/sonarlint/intellij/ui/tree/TaintVulnerabilityTree.kt, src/main/java/org/sonarlint/intellij/ui/vulnerabilities/TaintVulnerabilitiesPanel.kt, src/main/java/org/sonarlint/intellij/util/DataKeys.kt, src/main/resources/META-INF/plugin.xml
=> SLI-972 Add user interactions to review issue

gradle.properties, src/main/java/org/sonarlint/intellij/actions/MarkAsResolvedAction.kt, src/main/java/org/sonarlint/intellij/finding/issue/vulnerabilities/LocalTaintVulnerability.kt, src/main/java/org/sonarlint/intellij/ui/resolve/MarkAsResolvedDialog.kt, src/main/java/org/sonarlint/intellij/ui/resolve/MarkAsResolvedOptionPanel.kt, src/main/java/org/sonarlint/intellij/ui/resolve/MarkAsResolvedPanel.kt
=> SLI-973 Create the review dialog

build.gradle.kts
Tested the same way as for SonarLint for Eclipse
=> SLI-1000: Python analyzer update

clion/src/main/java/org/sonarlint/intellij/clion/AnalyzerConfiguration.java
Related CFamily ticket: https://sonarsource.atlassian.net/browse/CPP-4403.
=> SLI-955 Use CLion detected language for header files

.cirrus.yml, build.gradle.kts, gradle.properties
- use t3.xlarge
- allocate more memory to mend scan
=> BUILD-3063 improvements

gradle.properties
Update to the released artifact instead of using the dogfooding version
=> SLCORE update

.cirrus.yml
Following https://sonarsource.atlassian.net/browse/BUILD-3483?focusedCommentId=513295 comment because same issue happened
=> Increase CIRRUS_CLONE_DEPTH to 50

build.gradle.kts
=> Fix okio-jvm 3.0.0 CVE

.cirrus.yml
Tested by interactively executing the commands on CirrusCI
=> BUILD-3523 Fix version missing from dogfood.json

build.gradle.kts
Update is done via `sonarlint-omnisharp`
=> SLI-1072: C# analyzer update

git/src/main/kotlin/org/sonarlint/intellij/git/GitRepo.kt, src/main/java/org/sonarlint/intellij/finding/TextRangeMatcher.java, src/main/java/org/sonarlint/intellij/finding/tracking/LocalHistoryFindingTracker.kt, src/main/java/org/sonarlint/intellij/ui/CardPanel.kt, src/main/java/org/sonarlint/intellij/ui/nodes/IssueNode.java, src/main/java/org/sonarlint/intellij/vcs/DefaultVcsService.kt
=> Fix SQ bugs

build.gradle.kts
There are some ScheduledForRemoval API usages, but we will take care of them later
=> Relax plugin verifier

src/main/java/org/sonarlint/intellij/config/global/wizard/ConfirmStep.java, src/main/java/org/sonarlint/intellij/notifications/SonarLintProjectNotifications.java
Since we increased the minimal version we support for IntelliJ, we only support 'create' and not 'finish' anymore (https://github.com/JetBrains/intellij-community/commit/b0392e7871d6f310d89a25b5c69b67d4c1244e05)
=> Hardening round 10.3

src/main/java/org/sonarlint/intellij/config/global/AutomaticServerConnectionCreator.kt, src/main/resources/META-INF/plugin.xml
Following PM's feedback, the **features and benefits** text should be a link to the doc
=> SLI-1221 Automatic connected mode setup, missing opening link

src/main/java/org/sonarlint/intellij/documentation/SonarLintDocumentation.kt
The Clean Code attributes pages were recently improved in the Docs.
This PR updates the destination URL.
A redirect will be requested in the interim.
=> update new Clean Code landing URL

src/test/java/org/sonarlint/intellij/analysis/AnalysisTests.java
My understanding is that the analysis is not necessarily ready yet, so waiting should fix the issue
=> Fix flaky tests about module analysis

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/fs/ClientModuleVirtualFileEvent.kt, src/main/java/org/sonarlint/intellij/fs/DefaultVirtualFileSystemEventsHandler.kt, src/main/java/org/sonarlint/intellij/fs/EditorFileChangeListener.kt, src/main/java/org/sonarlint/intellij/fs/IdeaClientModuleFileEventBuilder.kt, src/main/java/org/sonarlint/intellij/util/SonarLintAppUtils.java, src/test/java/org/sonarlint/intellij/fs/VirtualFileSystemListenerTests.kt
Send all files to the backend, but only py & rider for engine
=> SLI-1345 SonarLint should send updates for any file system events

clion-resharper/src/main/java/org/sonarlint/intellij/clion/resharper/CFamilyAnalysisConfigurator.java, clion-resharper/src/main/java/org/sonarlint/intellij/clion/resharper/CLionResharperAnalyzerConfiguration.java, clion/src/main/java/org/sonarlint/intellij/clion/CFamilyAnalysisConfigurator.java, clion/src/main/java/org/sonarlint/intellij/clion/CFamilyFileExclusionContributor.java, settings.gradle.kts, src/main/resources/META-INF/plugin.xml
Based on JetBrains VIM dependencies: https://github.com/JetBrains/ideavim/blob/b86ec03dc4c02ad7b5c7f0f0bfd763a26aafd088/src/main/resources/META-INF/plugin.xml#L40
Plugin verifier result: https://cirrus-ci.com/build/4749474076033024
=> SLI-1400 Fix compatibility issues and optimize plugin dependency

src/main/java/org/sonarlint/intellij/config/global/ServerConnectionMgmtPanel.java
=> SLI-1357 List of connections should not be hidden

.cirrus.yml
Getting rid of Burgr prior to 31st of July.
=> SLI-1481: Decommission Burgr

.cirrus.yml
=> BUILD-5553 Changing Vault key names du to refactoring

src/main/java/org/sonarlint/intellij/fix/ShowFixSuggestion.kt, src/main/java/org/sonarlint/intellij/ui/inlay/InlayManager.kt
[SLI-1552](https://sonarsource.atlassian.net/browse/SLI-1552)
[SLI-1552]: https://sonarsource.atlassian.net/browse/SLI-1552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1552 Avoid Open Fix Suggestion duplication

its/src/test/kotlin/org/sonarlint/intellij/its/tests/OpenInIdeTests.kt, src/main/java/org/sonarlint/intellij/fix/ShowFixSuggestion.kt
[SLI-1553](https://sonarsource.atlassian.net/browse/SLI-1553)
[SLI-1553]: https://sonarsource.atlassian.net/browse/SLI-1553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1553 Avoid showing file content changed notification when not needed

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/fix/ShowFixSuggestion.kt, src/main/java/org/sonarlint/intellij/ui/inlay/InlayManager.kt
[SLI-1557](https://sonarsource.atlassian.net/browse/SLI-1557)
[SLI-1557]: https://sonarsource.atlassian.net/browse/SLI-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1557 Improve AI fix suggestion

common/src/main/java/org/sonarlint/intellij/common/util/SonarLintUtils.java, src/main/java/org/sonarlint/intellij/ui/CurrentFileConnectedModePanel.java, src/test/java/org/sonarlint/intellij/util/SonarLintUtilsTests.java
[SLI-1542](https://sonarsource.atlassian.net/browse/SLI-1542)
[SLI-1542]: https://sonarsource.atlassian.net/browse/SLI-1542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1542 Connection URL should be trimmed

src/main/java/org/sonarlint/intellij/config/global/rules/RuleConfigurationPanel.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ErrorPainter.java
[SLI-1426](https://sonarsource.atlassian.net/browse/SLI-1426)
[SLI-1426]: https://sonarsource.atlassian.net/browse/SLI-1426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1426 Should use invokeLater with correct modality state

build.gradle.kts, clion-common/build.gradle.kts, clion-resharper/build.gradle.kts, clion/build.gradle.kts, its/build.gradle.kts, settings.gradle.kts
[SLI-1480](https://sonarsource.atlassian.net/browse/SLI-1480)
[SLI-1480]: https://sonarsource.atlassian.net/browse/SLI-1480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1480 Re introduce code coverage metric on SonarQube

.cirrus.yml, build.gradle.kts, clion-common/build.gradle.kts, clion-resharper/build.gradle.kts, clion/build.gradle.kts, common/build.gradle.kts, git/build.gradle.kts, rider/build.gradle.kts
[SLI-1565](https://sonarsource.atlassian.net/browse/SLI-1565)
[SLI-1565]: https://sonarsource.atlassian.net/browse/SLI-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1565 Verify caching IDE distribution works

.cirrus.yml
[SLI-1524](https://sonarsource.atlassian.net/browse/SLI-1524)
[SLI-1524]: https://sonarsource.atlassian.net/browse/SLI-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1524 Re-enable dogfooding on master

build.gradle.kts, gradle/libs.versions.toml, its/build.gradle.kts, src/main/java/org/sonarlint/intellij/ui/vulnerabilities/tree/render/LocalTaintVulnerabilityRenderer.kt
[SLI-1569](https://sonarsource.atlassian.net/browse/SLI-1569)
[SLI-1569]: https://sonarsource.atlassian.net/browse/SLI-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1569 Update dependencies

.cirrus.yml, gradle/libs.versions.toml, src/main/resources/META-INF/plugin.xml, src/test/java/org/sonarlint/intellij/mediumtests/StandaloneModeMediumTests.kt
[SLI-1575](https://sonarsource.atlassian.net/browse/SLI-1575)
[SLI-1575]: https://sonarsource.atlassian.net/browse/SLI-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1575 Update change notes and SLCORE for 10.9

gradle.properties
[SLI-1576](https://sonarsource.atlassian.net/browse/SLI-1576)
[SLI-1576]: https://sonarsource.atlassian.net/browse/SLI-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1576 Prepare next dev iteration

src/main/java/org/sonarlint/intellij/ui/AbstractIssuesPanel.java
[SLI-1594](https://sonarsource.atlassian.net/browse/SLI-1594)
[SLI-1594]: https://sonarsource.atlassian.net/browse/SLI-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1594 Should be able to find old findings in the tree

rider/src/main/java/org/sonarlint/intellij/rider/RiderSolutionGitRepoProvider.kt
[SLI-1591](https://sonarsource.atlassian.net/browse/SLI-1591)
[SLI-1591]: https://sonarsource.atlassian.net/browse/SLI-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1591 Check if git4idea available in Rider

src/main/java/org/sonarlint/intellij/analysis/Analysis.java, src/main/java/org/sonarlint/intellij/fix/ShowFixSuggestion.kt, src/main/java/org/sonarlint/intellij/promotion/PromotionProvider.kt, src/main/java/org/sonarlint/intellij/ui/CurrentFileConnectedModePanel.java
[SLI-1589](https://sonarsource.atlassian.net/browse/SLI-1589)
[SLI-1589]: https://sonarsource.atlassian.net/browse/SLI-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1589 Improve UI Thread usage

src/main/java/org/sonarlint/intellij/ui/CurrentFileConnectedModePanel.java
[SLI-1597](https://sonarsource.atlassian.net/browse/SLI-1597)
[SLI-1597]: https://sonarsource.atlassian.net/browse/SLI-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1597 Remove useless curly braces for QG

src/main/java/org/sonarlint/intellij/errorsubmitter/BlameSonarSource.java, src/test/java/org/sonarlint/intellij/errorsubmitter/BlameSonarSourceTests.java
[SLI-1606](https://sonarsource.atlassian.net/browse/SLI-1606)
[SLI-1606]: https://sonarsource.atlassian.net/browse/SLI-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1606 Optimize error blame URL length

src/main/java/org/sonarlint/intellij/actions/MarkAsResolvedAction.kt, src/main/java/org/sonarlint/intellij/ui/resolve/MarkAsResolvedDialog.kt
[SLI-1604](https://sonarsource.atlassian.net/browse/SLI-1604)
[SLI-1604]: https://sonarsource.atlassian.net/browse/SLI-1604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1604 Should display error when no permission to resolve issue

.github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, docs/PULL_REQUEST_TEMPLATE.md
=> SLI-1605 Jira integration: Use repo vault token

src/main/java/org/sonarlint/intellij/actions/MarkAsResolvedAction.kt, src/main/java/org/sonarlint/intellij/actions/ReopenIssueAction.kt, src/main/java/org/sonarlint/intellij/actions/SonarLintToolWindow.java, src/main/java/org/sonarlint/intellij/finding/Issue.kt, src/main/java/org/sonarlint/intellij/finding/hotspot/LiveSecurityHotspot.java, src/main/java/org/sonarlint/intellij/finding/issue/LiveIssue.java, src/main/java/org/sonarlint/intellij/finding/issue/vulnerabilities/LocalTaintVulnerability.kt, src/main/java/org/sonarlint/intellij/ui/CurrentFilePanel.java, src/main/java/org/sonarlint/intellij/ui/ReportPanel.java, src/main/java/org/sonarlint/intellij/ui/review/ReviewSecurityHotspotDialog.kt, src/main/java/org/sonarlint/intellij/ui/tree/IssueTreeModelBuilder.java
[SLI-1608](https://sonarsource.atlassian.net/browse/SLI-1608)
[SLI-1608]: https://sonarsource.atlassian.net/browse/SLI-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1608 Security hotspot is not cleared from tree after marked as safe

src/main/java/org/sonarlint/intellij/core/BackendService.kt
[SLI-1612](https://sonarsource.atlassian.net/browse/SLI-1612)
[SLI-1612]: https://sonarsource.atlassian.net/browse/SLI-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1612 Handle cases where organizationKey is null

src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalOptionsPanel.java, src/main/java/org/sonarlint/intellij/config/global/rules/RuleConfigurationPanel.java
[SLI-1618](https://sonarsource.atlassian.net/browse/SLI-1618)
[SLI-1618]: https://sonarsource.atlassian.net/browse/SLI-1618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1618 Fix Quality Gate

its/src/test/kotlin/org/sonarlint/intellij/its/fixtures/FileBrowserDialogFixture.kt, src/main/java/org/sonarlint/intellij/trigger/EditorOpenTrigger.java, src/test/java/org/sonarlint/intellij/trigger/EditorOpenTriggerTests.java
[SLI-1616](https://sonarsource.atlassian.net/browse/SLI-1616)
[SLI-1616]: https://sonarsource.atlassian.net/browse/SLI-1616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1616 Send file to backend when opening a file

common/src/main/java/org/sonarlint/intellij/common/util/FileUtils.kt, src/main/java/org/sonarlint/intellij/analysis/Analysis.java
[SLI-1615](https://sonarsource.atlassian.net/browse/SLI-1615)
[SLI-1615]: https://sonarsource.atlassian.net/browse/SLI-1615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1615 Force sending files to analyze on Rider

gradle/libs.versions.toml, its/src/test/kotlin/org/sonarlint/intellij/its/tests/StandaloneIdeaTests.kt, src/main/resources/META-INF/plugin.xml
[SLI-1614](https://sonarsource.atlassian.net/browse/SLI-1614)
[SLI-1607](https://sonarsource.atlassian.net/browse/SLI-1607)
[SLI-1601](https://sonarsource.atlassian.net/browse/SLI-1601)
[SLI-1609](https://sonarsource.atlassian.net/browse/SLI-1609)
[SLI-1614]: https://sonarsource.atlassian.net/browse/SLI-1614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLI-1607]: https://sonarsource.atlassian.net/browse/SLI-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLI-1601]: https://sonarsource.atlassian.net/browse/SLI-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLI-1609]: https://sonarsource.atlassian.net/browse/SLI-1609?atlOrigin=eyJpIjoiNWRkNTl …
=> SLI-1614 SLI-1607 SLI-1601 SLI-1609 Analyzers update

src/main/resources/META-INF/plugin.xml
[SLI-1619](https://sonarsource.atlassian.net/browse/SLI-1619)
[SLI-1619]: https://sonarsource.atlassian.net/browse/SLI-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1619 Update change notes for 10.10

src/main/java/org/sonarlint/intellij/config/global/wizard/AuthStep.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectBindPanel.java, src/main/java/org/sonarlint/intellij/notifications/ConfigureNotificationsAction.kt, src/main/java/org/sonarlint/intellij/tasks/CheckNotificationsSupportedTask.java, src/main/java/org/sonarlint/intellij/tasks/ConnectionTestTask.kt, src/main/java/org/sonarlint/intellij/tasks/GetOrganizationTask.java, src/main/java/org/sonarlint/intellij/tasks/GetOrganizationsTask.java, src/main/java/org/sonarlint/intellij/tasks/ServerDownloadProjectTask.java, src/main/java/org/sonarlint/intellij/util/ThreadUtils.kt
[SLI-1635](https://sonarsource.atlassian.net/browse/SLI-1635)
[SLI-1635]: https://sonarsource.atlassian.net/browse/SLI-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1635 Improve task behavior when failing

src/main/java/org/sonarlint/intellij/StartServicesOnProjectOpened.java, src/main/java/org/sonarlint/intellij/trigger/EditorChangeTrigger.java, src/main/java/org/sonarlint/intellij/trigger/EditorOpenTrigger.java, src/main/java/org/sonarlint/intellij/trigger/EventWatcher.kt, src/main/resources/META-INF/plugin.xml, src/test/java/org/sonarlint/intellij/trigger/EditorOpenTriggerTests.java
[SLI-881](https://sonarsource.atlassian.net/browse/SLI-881)
[SLI-881]: https://sonarsource.atlassian.net/browse/SLI-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-881 Group files in the same analysis when opening multiple files

common/src/main/java/org/sonarlint/intellij/common/util/FileUtils.kt, src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/actions/SonarAnalyzeAllFilesAction.java, src/main/java/org/sonarlint/intellij/actions/SonarAnalyzeFilesAction.java, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/fs/DefaultVirtualFileSystemEventsHandler.kt, src/main/java/org/sonarlint/intellij/util/ProjectUtils.java, src/main/java/org/sonarlint/intellij/util/SonarLintAppUtils.java, src/test/java/org/sonarlint/intellij/ui/nodes/FileNodeTests.java
[SLI-1387](https://sonarsource.atlassian.net/browse/SLI-1387)
[SLI-1387]: https://sonarsource.atlassian.net/browse/SLI-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1387 Avoid loading too many files in the file system

common/src/main/java/org/sonarlint/intellij/common/util/FileUtils.kt, rider/src/main/java/org/sonarlint/intellij/rider/RiderFilesContributor.kt, rider/src/main/java/org/sonarlint/intellij/rider/RiderSolutionGitRepoProvider.kt, src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/actions/ExcludeFileAction.kt, src/main/java/org/sonarlint/intellij/actions/SonarAnalyzeFilesAction.java, src/main/java/org/sonarlint/intellij/analysis/AnalysisSubmitter.java, src/main/java/org/sonarlint/intellij/analysis/LocalFileExclusions.java, src/main/java/org/sonarlint/intellij/analysis/SonarLintAnalyzer.java, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/fs/DefaultVirtualFileSystemEventsHandler.kt, src/main/java/org/sonarlint/intellij/fs/EditorFileChangeListener.kt, src/main/java/org/sonarlint/intellij/trigger/EditorChangeTrigger.java, src/main/java/org/sonarlint/intellij/trigger/EditorOpenTrigger.java, src/main/java/org/sonarlint/intellij/ui/AutoTriggerStatusPanel.java, src/main/java/org/sonarlint/intellij/ui/CurrentFileConnectedModePanel.java, src/main/java/org/sonarlint/intellij/util/Extensions.kt, src/main/java/org/sonarlint/intellij/util/ProjectUtils.java, src/main/java/org/sonarlint/intellij/util/SonarLintAppUtils.java, src/test/java/org/sonarlint/intellij/mediumtests/StandaloneModeMediumTests.kt
[SLI-1638](https://sonarsource.atlassian.net/browse/SLI-1638)
[SLI-1638]: https://sonarsource.atlassian.net/browse/SLI-1638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1638 Optimize loading of files

gradle/libs.versions.toml
[SLI-1639](https://sonarsource.atlassian.net/browse/SLI-1639)
[SLI-1639]: https://sonarsource.atlassian.net/browse/SLI-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1639 Update to released version of SLCORE

gradle/libs.versions.toml
[SLI-1645](https://sonarsource.atlassian.net/browse/SLI-1645)
[SLI-1645]: https://sonarsource.atlassian.net/browse/SLI-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1645 Update SLCORE

gradle.properties
[SLI-1646](https://sonarsource.atlassian.net/browse/SLI-1646)
[SLI-1646]: https://sonarsource.atlassian.net/browse/SLI-1646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1646 Prepare next development iteration

src/main/java/org/sonarlint/intellij/actions/MarkAsResolvedAction.kt, src/main/java/org/sonarlint/intellij/actions/ReopenIssueAction.kt, src/main/java/org/sonarlint/intellij/actions/SonarLintToolWindow.java, src/main/java/org/sonarlint/intellij/finding/Issue.kt, src/main/java/org/sonarlint/intellij/finding/issue/LiveIssue.java, src/main/java/org/sonarlint/intellij/finding/issue/vulnerabilities/LocalTaintVulnerability.kt, src/main/java/org/sonarlint/intellij/ui/CurrentFilePanel.java, src/main/java/org/sonarlint/intellij/ui/ReportPanel.java, src/main/java/org/sonarlint/intellij/ui/review/ReviewSecurityHotspotDialog.kt, src/main/java/org/sonarlint/intellij/ui/tree/IssueTreeModelBuilder.java, src/main/java/org/sonarlint/intellij/ui/vulnerabilities/TaintVulnerabilitiesPanel.kt
[SLI-1647](https://sonarsource.atlassian.net/browse/SLI-1647)
[SLI-1647]: https://sonarsource.atlassian.net/browse/SLI-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1647 Marking issues as resolved does not reflect on UI

src/main/java/org/sonarlint/intellij/analysis/AnalysisSubmitter.java, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/trigger/EditorOpenTrigger.java, src/main/java/org/sonarlint/intellij/trigger/EventScheduler.kt, src/main/java/org/sonarlint/intellij/util/SonarLintAppUtils.java
[SLI-1656](https://sonarsource.atlassian.net/browse/SLI-1656)
[SLI-1656]: https://sonarsource.atlassian.net/browse/SLI-1656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1656 Should automatically analyze opened file on remote env

git/src/main/kotlin/org/sonarlint/intellij/git/GitRepo.kt
[SLI-1381](https://sonarsource.atlassian.net/browse/SLI-1381)
[SLI-1381]: https://sonarsource.atlassian.net/browse/SLI-1381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1381 Error when a background task has no ProgressIndicator or Job

src/main/java/org/sonarlint/intellij/config/global/SonarLintAboutPanel.java
[SLI-1664](https://sonarsource.atlassian.net/browse/SLI-1664)
[SLI-1664]: https://sonarsource.atlassian.net/browse/SLI-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1664 Telemetry update should be taken into account

gradle/libs.versions.toml, src/main/resources/META-INF/plugin.xml
[SLI-1662](https://sonarsource.atlassian.net/browse/SLI-1662)
[SLI-1662]: https://sonarsource.atlassian.net/browse/SLI-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1662 Update CFamily analyzer to 6.60.0.76379

gradle/libs.versions.toml, src/main/resources/META-INF/plugin.xml
[SLI-1689](https://sonarsource.atlassian.net/browse/SLI-1689)
[SLI-1689]: https://sonarsource.atlassian.net/browse/SLI-1689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1689 Upgrade to released version of SLCORE and update change notes

build.gradle.kts, gradle.properties
[SLI-1690](https://sonarsource.atlassian.net/browse/SLI-1690)
[SLI-1690]: https://sonarsource.atlassian.net/browse/SLI-1690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1690 Prepare next dev iteration

src/main/java/org/sonarlint/intellij/config/global/wizard/NotificationsStep.java, src/main/java/org/sonarlint/intellij/documentation/SonarLintDocumentation.kt
[SLI-1708](https://sonarsource.atlassian.net/browse/SLI-1708)
[SLI-1708]: https://sonarsource.atlassian.net/browse/SLI-1708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1708 Link to SQ:C documentation about smart notif is broken

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/fs/VirtualFileEvent.kt, src/main/java/org/sonarlint/intellij/util/VirtualFileUtils.kt
[SLI-1702](https://sonarsource.atlassian.net/browse/SLI-1702)
[SLI-1702]: https://sonarsource.atlassian.net/browse/SLI-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1702 Get charset without reading file content

gradle/libs.versions.toml, src/main/resources/META-INF/plugin.xml
[SLI-1714](https://sonarsource.atlassian.net/browse/SLI-1714)
[SLI-1713](https://sonarsource.atlassian.net/browse/SLI-1713)
[SLI-1712](https://sonarsource.atlassian.net/browse/SLI-1712)
[SLI-1714]: https://sonarsource.atlassian.net/browse/SLI-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLI-1713]: https://sonarsource.atlassian.net/browse/SLI-1713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLI-1712]: https://sonarsource.atlassian.net/browse/SLI-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1714 SLI-1713 SLI-1712 Analyzer updates for 10.13

src/main/java/org/sonarlint/intellij/config/global/GlobalExclusionsPanel.java, src/main/java/org/sonarlint/intellij/config/global/ServerConnectionMgmtPanel.java
[SLI-1717](https://sonarsource.atlassian.net/browse/SLI-1717)
[SLI-1717]: https://sonarsource.atlassian.net/browse/SLI-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1717 Fix rebranding icons

.cirrus.yml, README.md, build.gradle.kts, clion-common/build.gradle.kts, clion-resharper/build.gradle.kts, clion/build.gradle.kts, gradle.properties, rider/build.gradle.kts
Make use of https://github.com/SonarSource/sonarlint-ci-images/pull/24
- **SLI-1710 Use custom AMI Windows Image**
- **SLI-1710 use pr-24-sonarlint-intellij image**
Part of 
* Please review our [contribution guidelines](https://github.com/SonarSource/sonarlint-intellij/blob/master/contributing.md).
=> SLI-1710 sonarlint-intellij golden based image

gradle/libs.versions.toml, src/main/java/org/sonarlint/intellij/core/BackendService.kt
[SLI-1744](https://sonarsource.atlassian.net/browse/SLI-1744)
[SLI-1744]: https://sonarsource.atlassian.net/browse/SLI-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1744 Distinguish between added and modified files

build.gradle.kts, src/main/java/org/sonarlint/intellij/analysis/Analysis.java, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/fs/DefaultVirtualFileSystemEventsHandler.kt, src/main/java/org/sonarlint/intellij/fs/EditorFileChangeListener.kt, src/main/java/org/sonarlint/intellij/trigger/EditorOpenTrigger.java, src/test/java/org/sonarlint/intellij/analysis/AnalysisTests.java, src/test/java/org/sonarlint/intellij/fs/VirtualFileSystemListenerTests.kt, src/test/java/org/sonarlint/intellij/mediumtests/StandaloneModeMediumTests.kt
[SLI-1741](https://sonarsource.atlassian.net/browse/SLI-1741)
[SLI-1741]: https://sonarsource.atlassian.net/browse/SLI-1741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1741 Avoid sending file content for any file event in the project

src/main/java/org/sonarlint/intellij/documentation/SonarLintDocumentation.kt, src/test/java/org/sonarlint/intellij/documentation/SonarLintDocumentationTests.kt
[SLI-1680](https://sonarsource.atlassian.net/browse/SLI-1680)
[SLI-1680]: https://sonarsource.atlassian.net/browse/SLI-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1680 Update documentation links to match the rebranding

NOTICE.txt, clion-resharper/build.gradle.kts, clion/build.gradle.kts
[SLI-1716](https://sonarsource.atlassian.net/browse/SLI-1716)
[SLI-1716]: https://sonarsource.atlassian.net/browse/SLI-1716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1716 Update NOTICE.txt

clion/src/main/java/org/sonarlint/intellij/clion/CLionAnalyzerConfiguration.java
[SLI-1675](https://sonarsource.atlassian.net/browse/SLI-1675)
[SLI-1675]: https://sonarsource.atlassian.net/browse/SLI-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1675 Avoid 'Symbol building is not allowed' errors

gradle/libs.versions.toml
[SLI-1756](https://sonarsource.atlassian.net/browse/SLI-1756)
[SLI-1756]: https://sonarsource.atlassian.net/browse/SLI-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1756 Use released version of SLCORE

gradle/libs.versions.toml
[SLI-1759](https://sonarsource.atlassian.net/browse/SLI-1759)
[SLI-1759]: https://sonarsource.atlassian.net/browse/SLI-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1759 Update to latest released version of SLCORE

gradle/libs.versions.toml
[SLI-1767](https://sonarsource.atlassian.net/browse/SLI-1767)
[SLI-1767]: https://sonarsource.atlassian.net/browse/SLI-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1767 Update to released version 10.11.2 of SLCORE

git/src/main/kotlin/org/sonarlint/intellij/git/GitRepo.kt, src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
[SLI-1734](https://sonarsource.atlassian.net/browse/SLI-1734)
[SLI-1734]: https://sonarsource.atlassian.net/browse/SLI-1734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1734 Use ProgressIndicator to compute git information

.cirrus.yml
[SLI-1773](https://sonarsource.atlassian.net/browse/SLI-1773)
[SLI-1773]: https://sonarsource.atlassian.net/browse/SLI-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1773 Update PR and Maintained branches

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/core/EnabledLanguages.kt, src/main/java/org/sonarlint/intellij/finding/TextRangeMatcher.java, src/main/java/org/sonarlint/intellij/util/VirtualFileUtils.kt, src/test/java/org/sonarlint/intellij/finding/TextRangeMatcherTest.kt, src/test/java/org/sonarlint/intellij/util/VirtualFileUtilsTests.kt
[SLI-1751](https://sonarsource.atlassian.net/browse/SLI-1751)
[SLI-1751]: https://sonarsource.atlassian.net/browse/SLI-1751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1751 Support analysis of Python Notebooks

gradle/libs.versions.toml, src/main/resources/META-INF/plugin.xml
[SLI-1777](https://sonarsource.atlassian.net/browse/SLI-1777)
[SLI-1777]: https://sonarsource.atlassian.net/browse/SLI-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1777 Prepare release 10.14

gradle.properties, gradle/libs.versions.toml, src/main/resources/META-INF/plugin.xml
[SLI-1791](https://sonarsource.atlassian.net/browse/SLI-1791)
[SLI-1791]: https://sonarsource.atlassian.net/browse/SLI-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1791 Prepare for bugfix release

gradle.properties
[SLI-1792](https://sonarsource.atlassian.net/browse/SLI-1792)
[SLI-1792]: https://sonarsource.atlassian.net/browse/SLI-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1792 Prepare next dev iteration

.cirrus.yml, build.gradle.kts
[SLI-1794](https://sonarsource.atlassian.net/browse/SLI-1794)
[SLI-1794]: https://sonarsource.atlassian.net/browse/SLI-1794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1794 Run the plugin verifier on 2024.3.1

git/src/main/kotlin/org/sonarlint/intellij/git/GitRepo.kt, src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
[SLI-1786](https://sonarsource.atlassian.net/browse/SLI-1786)
[SLI-1786]: https://sonarsource.atlassian.net/browse/SLI-1786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1786 Do no display a modal when computing branch information

its/src/test/kotlin/org/sonarlint/intellij/its/utils/OrchestratorUtils.kt
[SLI-1808](https://sonarsource.atlassian.net/browse/SLI-1808)
[SLI-1808]: https://sonarsource.atlassian.net/browse/SLI-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1808 Remove `sonar.password` from SonarQube Server ITs

gradle.properties
[SLI-1811](https://sonarsource.atlassian.net/browse/SLI-1811)
[SLI-1811]: https://sonarsource.atlassian.net/browse/SLI-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1811 Prepare next dev iteration

gradle/libs.versions.toml, src/main/java/org/sonarlint/intellij/core/BackendService.kt
[SLI-1815](https://sonarsource.atlassian.net/browse/SLI-1815)
[SLI-1815]: https://sonarsource.atlassian.net/browse/SLI-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1815 Update to released version of SLCORE

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/actions/DisableRuleAction.java, src/main/java/org/sonarlint/intellij/actions/ExcludeFileAction.kt, src/main/java/org/sonarlint/intellij/analysis/AnalysisSubmitter.java, src/main/java/org/sonarlint/intellij/analysis/OnTheFlyFindingsHolder.kt, src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalConfigurable.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectConfigurable.java, src/main/java/org/sonarlint/intellij/editor/DisableRuleIntentionAction.java, src/main/java/org/sonarlint/intellij/trigger/BuildFinishedAnalysisTrigger.java, src/main/java/org/sonarlint/intellij/trigger/CompilationFinishedAnalysisTrigger.java, src/main/java/org/sonarlint/intellij/trigger/EditorOpenTrigger.java, src/main/java/org/sonarlint/intellij/trigger/TriggerType.kt, src/test/java/org/sonarlint/intellij/trigger/BuildFinishedAnalysisTriggerTests.java, src/test/java/org/sonarlint/intellij/trigger/CompilationFinishedAnalysisTriggerTests.java, src/test/java/org/sonarlint/intellij/trigger/EditorChangeTriggerTests.java, src/test/java/org/sonarlint/intellij/trigger/EditorOpenTriggerTests.java
[SLI-1805](https://sonarsource.atlassian.net/browse/SLI-1805)
[SLI-1805]: https://sonarsource.atlassian.net/browse/SLI-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1805 Avoid non-needed analysis triggering

gradle/libs.versions.toml, src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/config/global/wizard/AuthStep.java, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/sharing/AutomaticSharedConfigCreator.kt, src/test/java/org/sonarlint/intellij/finding/issue/IssueFixtures.kt
[SLI-1803](https://sonarsource.atlassian.net/browse/SLI-1803)
[SLI-1803]: https://sonarsource.atlassian.net/browse/SLI-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1803 Stop using SLCORE deprecated APIs

.cirrus.yml, README.md, build.gradle.kts, its/src/test/kotlin/org/sonarlint/intellij/its/utils/SonarCloudUtils.kt
[SLI-1801](https://sonarsource.atlassian.net/browse/SLI-1801)
Switching from username/password authentication.
[SLI-1801]: https://sonarsource.atlassian.net/browse/SLI-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1801: Token for SonarQube Cloud ITs

gradle/libs.versions.toml, src/main/resources/META-INF/plugin.xml
[SLI-1841](https://sonarsource.atlassian.net/browse/SLI-1841)
[SLI-1823](https://sonarsource.atlassian.net/browse/SLI-1823)
[SLI-1841]: https://sonarsource.atlassian.net/browse/SLI-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLI-1823]: https://sonarsource.atlassian.net/browse/SLI-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1841 SLI-1823 Update C# analyzer, change notes and update released version of SLCORE

gradle.properties
[SLI-1847](https://sonarsource.atlassian.net/browse/SLI-1847)
[SLI-1847]: https://sonarsource.atlassian.net/browse/SLI-1847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1847 Prepare next dev iteration

gradle.properties, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/resources/META-INF/plugin.xml
[SLI-1848](https://sonarsource.atlassian.net/browse/SLI-1848)
[SLI-1848]: https://sonarsource.atlassian.net/browse/SLI-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1848 Add back SonarLint in the User-Agent

gradle.properties
[SLI-1849](https://sonarsource.atlassian.net/browse/SLI-1849)
[SLI-1849]: https://sonarsource.atlassian.net/browse/SLI-1849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1849 Prepare next development iteration

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
[SLI-1858](https://sonarsource.atlassian.net/browse/SLI-1858)
[SLI-1858]: https://sonarsource.atlassian.net/browse/SLI-1858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1858 Do not log if project is not available during branch matching

src/main/java/org/sonarlint/intellij/finding/TextRangeMatcher.java, src/main/java/org/sonarlint/intellij/ui/vulnerabilities/TaintVulnerabilitiesPanel.kt
[SLI-1821](https://sonarsource.atlassian.net/browse/SLI-1821)
[SLI-1821]: https://sonarsource.atlassian.net/browse/SLI-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1821 Avoid throwing errors from read actions

gradle/libs.versions.toml
[SLI-1860](https://sonarsource.atlassian.net/browse/SLI-1860)
[SLI-1860]: https://sonarsource.atlassian.net/browse/SLI-1860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1860 Update to latest version of SLCORE

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/analysis/AnalysisSubmitter.java, src/main/java/org/sonarlint/intellij/analysis/OnTheFlyFindingsHolder.kt, src/main/java/org/sonarlint/intellij/trigger/TriggerType.kt
[SLI-1857](https://sonarsource.atlassian.net/browse/SLI-1857)
[SLI-1857]: https://sonarsource.atlassian.net/browse/SLI-1857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1857 Selecting a new file in the editor should trigger an analysis

src/main/java/org/sonarlint/intellij/documentation/SonarLintDocumentation.kt
[DOC-1835](https://sonarsource.atlassian.net/browse/DOC-1835)
[DOC-1835]: https://sonarsource.atlassian.net/browse/DOC-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-1835 rebrand docs URL

src/main/java/org/sonarlint/intellij/analysis/LocalFileExclusions.java, src/test/java/org/sonarlint/intellij/actions/ClearReportActionTests.java, src/test/java/org/sonarlint/intellij/analysis/LocalFileExclusionsTests.java
[SLI-1862](https://sonarsource.atlassian.net/browse/SLI-1862)
[SLI-1862]: https://sonarsource.atlassian.net/browse/SLI-1862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1862 Partial class with razor should not be analyzed

src/main/java/org/sonarlint/intellij/core/EnabledLanguages.kt
[SLI-1864](https://sonarsource.atlassian.net/browse/SLI-1864)
[SLI-1864]: https://sonarsource.atlassian.net/browse/SLI-1864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1864 Do not pass the C# embedded plugins to SLCORE

gradle/libs.versions.toml, src/main/resources/META-INF/plugin.xml
[SLI-1866](https://sonarsource.atlassian.net/browse/SLI-1866)
[SLI-1866]: https://sonarsource.atlassian.net/browse/SLI-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1866 Update change notes

gradle/libs.versions.toml
[SLI-1877](https://sonarsource.atlassian.net/browse/SLI-1877)
[SLI-1877]: https://sonarsource.atlassian.net/browse/SLI-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1877 Use dogfooding version of SLCORE (git native)

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt
[SLI-1882](https://sonarsource.atlassian.net/browse/SLI-1882)
We were sending the module's project as base dir, which can lead to problems. We should try to use the actual module's base dir.
[SLI-1882]: https://sonarsource.atlassian.net/browse/SLI-1882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1882 Base dir should be sent correctly for each module

gradle/libs.versions.toml, its/build.gradle.kts, src/main/java/org/sonarlint/intellij/SonarLintIcons.kt, src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/actions/SonarLintToolWindow.java, src/main/java/org/sonarlint/intellij/actions/SuggestCodeFixIntentionAction.kt, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/editor/SonarExternalAnnotator.java, src/main/java/org/sonarlint/intellij/finding/Finding.kt, src/main/java/org/sonarlint/intellij/finding/LiveFinding.java, src/main/java/org/sonarlint/intellij/finding/hotspot/LiveSecurityHotspot.java, src/main/java/org/sonarlint/intellij/finding/issue/LiveIssue.java, src/main/java/org/sonarlint/intellij/finding/issue/vulnerabilities/LocalTaintVulnerability.kt, src/main/java/org/sonarlint/intellij/fix/ShowFixSuggestion.kt, src/main/java/org/sonarlint/intellij/ui/AbstractIssuesPanel.java, src/main/java/org/sonarlint/intellij/ui/CurrentFilePanel.java, src/main/java/org/sonarlint/intellij/ui/FindingDetailsPanel.kt, src/main/java/org/sonarlint/intellij/ui/ReportPanel.java, src/main/java/org/sonarlint/intellij/ui/SecurityHotspotsPanel.java, src/main/java/org/sonarlint/intellij/ui/SonarLintRulePanel.kt, src/main/java/org/sonarlint/intellij/ui/codefix/CodeFixTabPanel.kt, src/main/java/org/sonarlint/intellij/ui/inlay/FixSuggestionInlayHolder.kt, src/main/java/org/sonarlint/intellij/ui/inlay/FixSuggestionInlayPanel.kt, src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleDescriptionPanel.kt, src/main/java/org/sonarlint/intellij/ui/tree/IssueTree.java, src/main/java/org/sonarlint/intellij/ui/tree/IssueTreeModelBuilder.java, src/main/java/org/sonarlint/intellij/ui/vulnerabilities/TaintVulnerabilitiesPanel.kt, src/main/java/org/sonarlint/intellij/ui/vulnerabilities/tree/TaintVulnerabilityTree.kt, src/main/resources/images/codefix.svg
[SLI-1832](https://sonarsource.atlassian.net/browse/SLI-1832)
[SLI-1832]: https://sonarsource.atlassian.net/browse/SLI-1832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1832 Handle the generation of AI fix suggestions

build.gradle.kts, its/build.gradle.kts, src/main/java/org/sonarlint/intellij/core/BackendService.kt
[SLI-1885](https://sonarsource.atlassian.net/browse/SLI-1885)
[SLI-1885]: https://sonarsource.atlassian.net/browse/SLI-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1885 Do not send Sentry telemetry on the CI environment

gradle/libs.versions.toml, src/main/resources/META-INF/plugin.xml
[SLI-1907](https://sonarsource.atlassian.net/browse/SLI-1907)
[SLI-1907]: https://sonarsource.atlassian.net/browse/SLI-1907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1907 Prepare release 10.18

gradle.properties, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectBindPanel.java
[SLI-1908](https://sonarsource.atlassian.net/browse/SLI-1908)
[SLI-1908]: https://sonarsource.atlassian.net/browse/SLI-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1908 Prepare next development iteration

its/build.gradle.kts, src/main/java/org/sonarlint/intellij/SonarLintIcons.kt, src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/actions/SonarLintToolWindow.java, src/main/java/org/sonarlint/intellij/actions/SuggestCodeFixIntentionAction.kt, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/editor/SonarExternalAnnotator.java, src/main/java/org/sonarlint/intellij/finding/Finding.kt, src/main/java/org/sonarlint/intellij/finding/LiveFinding.java, src/main/java/org/sonarlint/intellij/finding/hotspot/LiveSecurityHotspot.java, src/main/java/org/sonarlint/intellij/finding/issue/LiveIssue.java, src/main/java/org/sonarlint/intellij/finding/issue/vulnerabilities/LocalTaintVulnerability.kt, src/main/java/org/sonarlint/intellij/fix/ShowFixSuggestion.kt, src/main/java/org/sonarlint/intellij/ui/AbstractIssuesPanel.java, src/main/java/org/sonarlint/intellij/ui/CurrentFilePanel.java, src/main/java/org/sonarlint/intellij/ui/FindingDetailsPanel.kt, src/main/java/org/sonarlint/intellij/ui/ReportPanel.java, src/main/java/org/sonarlint/intellij/ui/SecurityHotspotsPanel.java, src/main/java/org/sonarlint/intellij/ui/SonarLintRulePanel.kt, src/main/java/org/sonarlint/intellij/ui/codefix/CodeFixTabPanel.kt, src/main/java/org/sonarlint/intellij/ui/inlay/FixSuggestionInlayHolder.kt, src/main/java/org/sonarlint/intellij/ui/inlay/FixSuggestionInlayPanel.kt, src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleDescriptionPanel.kt, src/main/java/org/sonarlint/intellij/ui/tree/IssueTree.java, src/main/java/org/sonarlint/intellij/ui/tree/IssueTreeModelBuilder.java, src/main/java/org/sonarlint/intellij/ui/vulnerabilities/TaintVulnerabilitiesPanel.kt, src/main/java/org/sonarlint/intellij/ui/vulnerabilities/tree/TaintVulnerabilityTree.kt, src/main/resources/images/codefix.svg
[SLI-1909](https://sonarsource.atlassian.net/browse/SLI-1909)
[SLI-1909]: https://sonarsource.atlassian.net/browse/SLI-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1909 Put back AI CodeFix into dogfooding

src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalOptionsPanel.java
[SLI-1859](https://sonarsource.atlassian.net/browse/SLI-1859)
[SLI-1859]: https://sonarsource.atlassian.net/browse/SLI-1859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1859 Do not allow to pass an invalid path for Node.js

.github/workflows/PullRequestClosed.yml
[SLI-1918](https://sonarsource.atlassian.net/browse/SLI-1918)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SLI-1918]: https://sonarsource.atlassian.net/browse/SLI-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1918 Autoclose issues created by Jira integration

src/main/java/org/sonarlint/intellij/fix/FixSuggestionSnippet.kt, src/main/java/org/sonarlint/intellij/fix/ShowFixSuggestion.kt, src/main/java/org/sonarlint/intellij/ui/codefix/CodeFixDiffView.kt, src/main/java/org/sonarlint/intellij/ui/inlay/FixSuggestionInlayHolder.kt, src/main/java/org/sonarlint/intellij/ui/inlay/FixSuggestionInlayPanel.kt, src/main/java/org/sonarlint/intellij/ui/inlay/InlayManager.kt, src/test/java/org/sonarlint/intellij/ui/inlay/FixSuggestionInlayHolderTests.kt
[SLI-1917](https://sonarsource.atlassian.net/browse/SLI-1917)
[SLI-1917]: https://sonarsource.atlassian.net/browse/SLI-1917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1917 AI CodeFix improvements - Navigable snippets, adjusted diff

common/src/main/java/org/sonarlint/intellij/common/util/SonarLintUtils.java, src/main/java/org/sonarlint/intellij/config/global/AutomaticServerConnectionCreator.kt, src/main/java/org/sonarlint/intellij/config/global/ServerConnectionMgmtPanel.java, src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalOptionsPanel.java, src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalSettings.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ServerStep.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectBindPanel.java, src/main/java/org/sonarlint/intellij/sharing/AutomaticSharedConfigCreator.kt
[SLI-1897](https://sonarsource.atlassian.net/browse/SLI-1897)
[SLI-1897]: https://sonarsource.atlassian.net/browse/SLI-1897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1897 Create a setting for allowing connection to US

common/src/main/java/org/sonarlint/intellij/common/util/SonarLintUtils.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ServerStep.form
[SLI-1914](https://sonarsource.atlassian.net/browse/SLI-1914)
[SLI-1914]: https://sonarsource.atlassian.net/browse/SLI-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1914 Change US URL

clion-resharper/src/main/java/org/sonarlint/intellij/clion/resharper/CLionResharperAnalyzerConfiguration.java, clion-resharper/src/test/java/org/sonarlint/intellij/clion/resharper/CLionResharperAnalyzerConfigurationTest.java
[SLI-1467](https://sonarsource.atlassian.net/browse/SLI-1467)
[SLI-1467]: https://sonarsource.atlassian.net/browse/SLI-1467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1467 Fix OCLanguageKind retrieval in CLion Nova mode

gradle/libs.versions.toml
[SLI-1905](https://sonarsource.atlassian.net/browse/SLI-1905)
[SLI-1905]: https://sonarsource.atlassian.net/browse/SLI-1905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1905 Update embedded C# analyzer to 10.7.0.110445

src/main/java/org/sonarlint/intellij/config/global/ServerConnectionMgmtPanel.java
[SLI-1927](https://sonarsource.atlassian.net/browse/SLI-1927)
[SLI-1927]: https://sonarsource.atlassian.net/browse/SLI-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1927 Reduce connection list size

gradle.properties
[SLI-1936](https://sonarsource.atlassian.net/browse/SLI-1936)
[SLI-1936]: https://sonarsource.atlassian.net/browse/SLI-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1936 Prepare next development iteration

src/main/java/org/sonarlint/intellij/analysis/LocalFileExclusions.java
[SLI-1956](https://sonarsource.atlassian.net/browse/SLI-1956)
[SLI-1956]: https://sonarsource.atlassian.net/browse/SLI-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1956 Fix file exclusions on Windows

gradle.properties
[SLI-1967](https://sonarsource.atlassian.net/browse/SLI-1967)
[SLI-1967]: https://sonarsource.atlassian.net/browse/SLI-1967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1967 Prepare next development iteration

src/main/java/org/sonarlint/intellij/actions/SuggestCodeFixIntentionAction.kt
[SLI-1974](https://sonarsource.atlassian.net/browse/SLI-1974)
[SLI-1974]: https://sonarsource.atlassian.net/browse/SLI-1974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1974 Show the issue message for the AI CodeFix intention action

src/main/java/org/sonarlint/intellij/util/SonarLintActions.java
Hi!
Old text (SonarLint) in the UI. The new (SonarQube) is actual. It looks better, and consistent with the other buttons.
Minor modification.
404 - page not found: https://github.com/SonarSource/sonarlint-intellij/blob/master/contributing.md
=> SLI-1981 Correctly rebrand the "Clear Issues" action

its/src/test/kotlin/org/sonarlint/intellij/its/fixtures/Fixtures.kt, its/src/test/kotlin/org/sonarlint/intellij/its/tests/StandaloneIdeaTests.kt, its/src/test/kotlin/org/sonarlint/intellij/its/tests/domain/WalkthroughTests.kt
[SLI-1982](https://sonarsource.atlassian.net/browse/SLI-1982)
[SLI-1982]: https://sonarsource.atlassian.net/browse/SLI-1982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1982 Add UI Test for Walkthrough Opening

gradle.properties
[SLI-1995](https://sonarsource.atlassian.net/browse/SLI-1995)
[SLI-1995]: https://sonarsource.atlassian.net/browse/SLI-1995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1995 Prepare next development iteration

gradle.properties
[SLI-2014](https://sonarsource.atlassian.net/browse/SLI-2014)
[SLI-2014]: https://sonarsource.atlassian.net/browse/SLI-2014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2014 Prepare next development iteration

.cirrus.yml
[SLI-2023](https://sonarsource.atlassian.net/browse/SLI-2023)
[SLI-2023]: https://sonarsource.atlassian.net/browse/SLI-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2023 Update branch name for AMI QA

.cirrus.yml
[SLI-2023](https://sonarsource.atlassian.net/browse/SLI-2023)
[SLI-2023]: https://sonarsource.atlassian.net/browse/SLI-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2023 Remove branch name for AMI QA

gradle.properties
[SLI-2042](https://sonarsource.atlassian.net/browse/SLI-2042)
[SLI-2042]: https://sonarsource.atlassian.net/browse/SLI-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2042 Prepare next development iteration

src/main/java/org/sonarlint/intellij/ui/vulnerabilities/tree/render/LocalTaintVulnerabilityRenderer.kt
[SLI-1997](https://sonarsource.atlassian.net/browse/SLI-1997)
[SLI-1997]: https://sonarsource.atlassian.net/browse/SLI-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1997 Avoid slow actions while loading taints

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/config/global/rules/RuleConfigurationPanel.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectSettingsPanel.java, src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleParsingUtils.kt, src/main/java/org/sonarlint/intellij/ui/ruledescription/section/Section.kt, src/main/java/org/sonarlint/intellij/util/FutureUtils.java, src/main/java/org/sonarlint/intellij/util/ThreadUtils.kt
[SLI-2037](https://sonarsource.atlassian.net/browse/SLI-2037)
[SLI-2037]: https://sonarsource.atlassian.net/browse/SLI-2037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2037 Logs should be displayed for the related project when possible

src/test/java/org/sonarlint/intellij/trigger/EditorOpenTriggerTests.java
[SLI-2038](https://sonarsource.atlassian.net/browse/SLI-2038)
[SLI-2038]: https://sonarsource.atlassian.net/browse/SLI-2038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2038 Fix Flaky EditorOpenTrigger Test on Validate

src/main/java/org/sonarlint/intellij/config/global/NodeJsSettings.kt
[SLI-2062](https://sonarsource.atlassian.net/browse/SLI-2062)
[SLI-2062]: https://sonarsource.atlassian.net/browse/SLI-2062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2062 Should use the Node.js defined and saved in the settings

src/main/java/org/sonarlint/intellij/core/BackendService.kt
[SLI-2070](https://sonarsource.atlassian.net/browse/SLI-2070)
[SLI-2070]: https://sonarsource.atlassian.net/browse/SLI-2070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2070 Do not rely on deprecated initialization for SLOOP

gradle.properties
[SLI-2076](https://sonarsource.atlassian.net/browse/SLI-2076)
[SLI-2076]: https://sonarsource.atlassian.net/browse/SLI-2076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2076 Prepare next dev iteration

src/main/java/org/sonarlint/intellij/ui/codefix/CodeFixDiffView.kt
[SLI-2032](https://sonarsource.atlassian.net/browse/SLI-2032)
[SLI-2032]: https://sonarsource.atlassian.net/browse/SLI-2032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2032 Remove internal API usages

.cirrus.yml
[SLI-2030](https://sonarsource.atlassian.net/browse/SLI-2030)
[SLI-2030]: https://sonarsource.atlassian.net/browse/SLI-2030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2030 Run validate tasks in parallel of the build plugin task

.cirrus.yml
[SLI-2030](https://sonarsource.atlassian.net/browse/SLI-2030)
[SLI-2030]: https://sonarsource.atlassian.net/browse/SLI-2030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2030 Fix Mend scan due to missing project version

its/src/test/kotlin/org/sonarlint/intellij/its/tests/ConfigurationTests.kt, its/src/test/kotlin/org/sonarlint/intellij/its/tests/ConnectedAnalysisTests.kt, its/src/test/kotlin/org/sonarlint/intellij/its/tests/OpenInIdeTests.kt
[SLI-2103](https://sonarsource.atlassian.net/browse/SLI-2103)
[SLI-2103]: https://sonarsource.atlassian.net/browse/SLI-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2103 Fix Orchestrator by loading sonar-kotlin

src/main/java/org/sonarlint/intellij/core/BackendService.kt
[SLI-1171](https://sonarsource.atlassian.net/browse/SLI-1171)
[SLI-1171]: https://sonarsource.atlassian.net/browse/SLI-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1171 Use the project path as part of modules config scope IDs

src/main/java/org/sonarlint/intellij/core/BackendService.kt
[SLI-1771](https://sonarsource.atlassian.net/browse/SLI-1771)
[SLI-1771]: https://sonarsource.atlassian.net/browse/SLI-1771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1771 Remove unused import

src/main/java/org/sonarlint/intellij/core/BackendService.kt
[SLI-2126](https://sonarsource.atlassian.net/browse/SLI-2126)
[SLI-2126]: https://sonarsource.atlassian.net/browse/SLI-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2126 Analysis Should Work on Second Open Project

src/main/java/org/sonarlint/intellij/core/BackendService.kt
[SLI-2120](https://sonarsource.atlassian.net/browse/SLI-2120)
[SLI-2120]: https://sonarsource.atlassian.net/browse/SLI-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2120 Provide Omnisharp requirements only in Rider

src/main/java/org/sonarlint/intellij/analysis/AnalysisSubmitter.kt, src/main/java/org/sonarlint/intellij/tasks/GlobalTaskProgressReporter.kt
[SLI-1568](https://sonarsource.atlassian.net/browse/SLI-1568)
[SLI-1568]: https://sonarsource.atlassian.net/browse/SLI-1568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-1568 Do not show noisy task on open files

gradle.properties
[SLI-2137](https://sonarsource.atlassian.net/browse/SLI-2137)
[SLI-2137]: https://sonarsource.atlassian.net/browse/SLI-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2137 Prepare next development iteration

gradle.properties
[SLI-2168](https://sonarsource.atlassian.net/browse/SLI-2168)
[SLI-2168]: https://sonarsource.atlassian.net/browse/SLI-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2168 Prepare new iteration

README.md, src/main/java/org/sonarlint/intellij/config/global/ServerConnectionMgmtPanel.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ServerStep.java, src/main/java/org/sonarlint/intellij/sharing/AutomaticSharedConfigCreator.kt, src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleHeaderPanel.kt, src/main/java/org/sonarlint/intellij/ui/walkthrough/WalkthroughPanel.kt
[SLI-2149](https://sonarsource.atlassian.net/browse/SLI-2149)
[SLI-2149]: https://sonarsource.atlassian.net/browse/SLI-2149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2149 Remove Clean code occurrences

src/main/java/org/sonarlint/intellij/documentation/SonarLintDocumentation.kt, src/test/java/org/sonarlint/intellij/documentation/SonarLintDocumentationTests.kt
[DOC-2267](https://sonarsource.atlassian.net/browse/DOC-2267)
Clean code content has be renamed and the url slug has been updated.
Part of 
* Please review our [contribution guidelines](https://github.com/SonarSource/sonarlint-intellij/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines: 
[DOC-2267]: https://sonarsource.atlassian.net/browse/DOC-2267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2267 Update clean code url slug

src/main/java/org/sonarlint/intellij/ui/risks/DependencyRisksPanel.kt, src/main/resources/META-INF/plugin.xml
[MMF-4645](https://sonarsource.atlassian.net/browse/MMF-4645)
[MMF-4645]: https://sonarsource.atlassian.net/browse/MMF-4645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MMF-4645 Add SCA to change notes.

gradle.properties
[SLI-2196](https://sonarsource.atlassian.net/browse/SLI-2196)
[SLI-2196]: https://sonarsource.atlassian.net/browse/SLI-2196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2196 Prepare new iteration

README.md
[SLI-2197](https://sonarsource.atlassian.net/browse/SLI-2197)
[SLI-2197]: https://sonarsource.atlassian.net/browse/SLI-2197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2197 Update GitHub repo descriptions

.cirrus.yml, README.md, build.gradle.kts
[SLI-2223](https://sonarsource.atlassian.net/browse/SLI-2223)
[SLI-2223]: https://sonarsource.atlassian.net/browse/SLI-2223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2223 Refactor plugin verifier mechanism following 2.x migration

src/main/java/org/sonarlint/intellij/editor/SonarExternalAnnotator.java, src/main/java/org/sonarlint/intellij/ui/filter/FindingsFilter.kt, src/main/java/org/sonarlint/intellij/ui/report/ReportFilteringUtils.kt, src/main/java/org/sonarlint/intellij/ui/report/ReportPanel.kt, src/main/java/org/sonarlint/intellij/ui/report/ReportTreeManager.kt, src/main/java/org/sonarlint/intellij/ui/report/tree/ReportIssueTreeModelBuilder.kt, src/main/java/org/sonarlint/intellij/ui/report/tree/ReportSecurityHotspotTreeModelBuilder.kt, src/main/java/org/sonarlint/intellij/ui/report/tree/ReportTaintTreeModelBuilder.kt, src/main/java/org/sonarlint/intellij/ui/tree/FindingTreeSummary.kt, src/main/java/org/sonarlint/intellij/ui/tree/TreeContentKind.kt
[SLI-2227](https://sonarsource.atlassian.net/browse/SLI-2227)
[SLI-2227]: https://sonarsource.atlassian.net/browse/SLI-2227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2227 Add taints to the report tab

src/main/java/org/sonarlint/intellij/SonarLintIcons.kt, src/main/java/org/sonarlint/intellij/ui/currentfile/CurrentFilePanel.kt, src/main/java/org/sonarlint/intellij/ui/currentfile/CurrentFileStatusPanel.java, src/main/java/org/sonarlint/intellij/ui/currentfile/CurrentFileSummaryPanel.kt, src/main/java/org/sonarlint/intellij/ui/currentfile/SummaryButton.kt, src/main/java/org/sonarlint/intellij/ui/filter/FiltersPanel.kt, src/main/java/org/sonarlint/intellij/ui/filter/FindingsFilter.kt, src/main/java/org/sonarlint/intellij/ui/report/ReportTabStatusPanel.kt, src/main/java/org/sonarlint/intellij/ui/ruledescription/RuleCodeSnippet.kt
[SLI-2227](https://sonarsource.atlassian.net/browse/SLI-2227)
[SLI-2227]: https://sonarsource.atlassian.net/browse/SLI-2227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2227 Hardening for the unified view

its/src/test/kotlin/org/sonarlint/intellij/its/fixtures/ConfigureConnectionDialog.kt, its/src/test/kotlin/org/sonarlint/intellij/its/tests/ConfigurationTests.kt, its/src/test/kotlin/org/sonarlint/intellij/its/tests/domain/ConnectionFromToolWindowTests.kt, its/src/test/kotlin/org/sonarlint/intellij/its/tests/domain/CurrentFileTabTests.kt, src/main/java/org/sonarlint/intellij/config/global/wizard/AuthStep.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ConnectionWizardModel.java, src/main/java/org/sonarlint/intellij/config/global/wizard/NotificationsStep.java, src/main/java/org/sonarlint/intellij/config/global/wizard/OrganizationStep.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ServerConnectionWizard.java, src/main/java/org/sonarlint/intellij/config/global/wizard/ServerStep.java, src/main/java/org/sonarlint/intellij/config/project/SonarLintProjectBindPanel.java, src/test/java/org/sonarlint/intellij/config/global/wizard/ConnectionWizardModelTests.java
[SLI-2194](https://sonarsource.atlassian.net/browse/SLI-2194)
[SLI-2194]: https://sonarsource.atlassian.net/browse/SLI-2194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2194 When new connection is created, select it in the project settings

gradle.properties
[SLI-2241](https://sonarsource.atlassian.net/browse/SLI-2241)
[SLI-2241]: https://sonarsource.atlassian.net/browse/SLI-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2241 Prepare next development iteration

.gitignore, gradle.properties
[SLI-2254](https://sonarsource.atlassian.net/browse/SLI-2254)
[SLI-2254]: https://sonarsource.atlassian.net/browse/SLI-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2254 Prepare next development iteration & git ignore update

src/main/java/org/sonarlint/intellij/SonarLintIntelliJClient.kt, src/main/java/org/sonarlint/intellij/actions/filters/AutoShareTokenExchangeAction.kt, src/main/java/org/sonarlint/intellij/core/BackendService.kt, src/main/java/org/sonarlint/intellij/core/ProjectBindingManager.java, src/main/java/org/sonarlint/intellij/notifications/SonarLintProjectNotifications.kt, src/main/java/org/sonarlint/intellij/notifications/binding/BindProjectAction.kt, src/main/java/org/sonarlint/intellij/notifications/binding/BindingSuggestion.kt, src/main/java/org/sonarlint/intellij/notifications/binding/ChooseBindingSuggestionAction.kt, src/main/java/org/sonarlint/intellij/sharing/AutomaticSharedConfigCreator.kt, src/main/java/org/sonarlint/intellij/sharing/ConfigurationSharing.kt, src/main/java/org/sonarlint/intellij/telemetry/SonarLintTelemetry.kt, src/main/java/org/sonarlint/intellij/ui/BindingSuggestionSelectionDialog.kt, src/test/java/org/sonarlint/intellij/AbstractSonarLintLightTests.java, src/test/java/org/sonarlint/intellij/core/BackendServiceTests.kt, src/test/java/org/sonarlint/intellij/core/ProjectBindingManagerTests.java
[SLI-2167](https://sonarsource.atlassian.net/browse/SLI-2167)
[SLI-2167]: https://sonarsource.atlassian.net/browse/SLI-2167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-2167 Adapt to New Binding Telemetry Architecture

src/main/java/org/sonarlint/intellij/config/global/SonarLintGlobalSettingsStore.java, src/main/java/org/sonarlint/intellij/config/global/credentials/CredentialsService.kt, src/main/java/org/sonarlint/intellij/dogfood/DogfoodCredentialsStore.java
[SLI-378](https://sonarsource.atlassian.net/browse/SLI-378)
[SLI-378]: https://sonarsource.atlassian.net/browse/SLI-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLI-378 Use another signature for saveSettings.
